### ISSUE TITLE
[Feature Request] Support for OpenStack V3 API

### ISSUE THREAD

**Issue by afritzler** [sequenceiq/cloudbreak#1006]
Hi,

I was wondering if there are any plans to support the V3 APIs in OpenStack. From looking at the code (https://github.com/sequenceiq/cloudbreak/blob/2729315af1fb996abc62834bc919cff925c5905d/cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/OpenStackClient.java#L45-L51):

```
public Access createAccess(CloudCredential credential) {
        KeystoneCredentialView osCredential = createKeystoneCredential(credential);
        return OSFactory.builder().endpoint(osCredential.getEndpoint())
                .credentials(osCredential.getUserName(), osCredential.getPassword())
                .tenantName(osCredential.getTenantName())
                .authenticate().getAccess();
    }
```

I was able to connect to our OpenStack landscape by modifying the code as the following:

```
public Access createAccess(CloudCredential credential) {
        KeystoneCredentialView osCredential = createKeystoneCredential(credential);
        return OSFactory.builderV3().endpoint(osCredential.getEndpoint())
                .credentials(osCredential.getUserName(), osCredential.getPassword())
                .domainName(osCredential.getTenantName())
                .authenticate().getAccess();
    }
```

Since OpenStack4J supports the V3 APIs it was an easy change. Of course this has to be done in a more intelligent way - e.g. by detecting the API version based on the provided endpoint URL.

Regards,
Andreas

**Comment by matyix** [comment]
Hi Andreas

Yes, we are working on support for different keystone API's - will let you know once it's there.

Janos

**Comment by akanto** [comment]
Hi Andreas,

V3 support has been added: https://github.com/sequenceiq/cloudbreak/commit/e4382b90e127c4170494ff53944c5e6f7b0c2be3

Attila
