### ISSUE TITLE
Ambari agent logs do not rotate filling up disks

### ISSUE THREAD

**Issue by afederic** [sequenceiq/cloudbreak#1064]
Hi,

I have successfully deployed HDP 2.3 with Coudbreak 1.0.3 on Openstack Juno. But the log file of the ambari-agent is filling up the volume /hadoop/fs1/logs on all the VMs. It seems that the logging handler defined in the agent code (class logging.handlers.RotatingFileHandler) that should rotate the file when it’s size is about 10MB is not working properly for same reason. However, if I restart the ambari-agent service in the docker container the log file is rotated.

For example, after running 2 hours I have a log file of 46MB
```
[root@docker-ambari tmp]# ll -h /var/log/ambari-agent/
total 46M
-rw-r–r– 1 root root  46M Oct 20 14:47 ambari-agent.log
-rw-r–r– 1 root root 260K Oct 20 14:47 ambari-agent.out
```
If I restart the service, the handler is invoked and the file is rotated
```
[root@docker-ambari tmp]# ambari-agent restart -v
Restarting ambari-agent
Verifying Python version compatibility…
Using python  /usr/bin/python2.6
Found ambari-agent PID: 65
Stopping ambari-agent
Removing PID file at /var/run/ambari-agent/ambari-agent.pid
tput: No value for $TERM and no -T specified
ambari-agent successfully stopped
tput: No value for $TERM and no -T specified
Verifying Python version compatibility…
Using python  /usr/bin/python2.6
Checking for previously running Ambari Agent…
Starting ambari-agent
Verifying ambari-agent process status…
tput: No value for $TERM and no -T specified
Ambari Agent successfully started
tput: No value for $TERM and no -T specified
Agent PID at: /var/run/ambari-agent/ambari-agent.pid
Agent out at: /var/log/ambari-agent/ambari-agent.out
Agent log at: /var/log/ambari-agent/ambari-agent.log

[root@docker-ambari tmp]# ll -h /var/log/ambari-agent/
total 48M
-rw-r–r– 1 root root 44K Oct 20 14:51 ambari-agent.log
-rw-r–r– 1 root root 48M Oct 20 14:51 ambari-agent.log.1
-rw-r–r– 1 root root   0 Oct 20 14:51 ambari-agent.out
```

Thanks
Ale

**Comment by martonsereg** [comment]
Thanks for reporting, we'll look into it.
I have one question though: 48M after 2 hours of running seems way too much. I currently have an Azure cluster running for 7 hours where I've checked these logs on the agents and it's no more than 2M.
What's inside those log files that fills up so quickly?

**Comment by afederic** [comment]
The startup script inside the container starts the ambari-agent in _verbose_ mode (-v switch)
```
[root@docker-ambari tmp]# grep -5 ambari-agent /start-agent
main() {
  cleanup-rpmdb
  local-nameserver
  reorder-dns-lookup
  set-server-ip
  ambari-agent start -v
  /etc/init.d/sshd start
  while true; do
    sleep 3
    tail -f /var/log/ambari-agent/ambari-agent.log
  done
}

main "$@"
```
The log file is full of DEBUG lines. Please also note that the 46MB file was generated after _about_ 2 hours from the cluster deploy (it was yesterday). Now the log is
```
[root@docker-ambari tmp]# ll -h /var/log/ambari-agent/
total 996M
-rw-r--r-- 1 root root 945M Oct 21 15:57 ambari-agent.log
-rw-r--r-- 1 root root  48M Oct 20 14:51 ambari-agent.log.1
-rw-r--r-- 1 root root 3.2M Oct 21 15:57 ambari-agent.out
```
Thanks
Ale

**Comment by martonsereg** [comment]
Can you share this logfile with us (the smaller one is ok)? Even with debug logging this shouldn't be more than a few MBs per day.

**Comment by afederic** [comment]
Yes, of course. It's [here](https://drive.google.com/file/d/0BybLFCD6QChCVTh1XzVTeXYwamM/view?usp=sharing).

**Comment by afederic** [comment]
Any news about it? My logs are getting bigger
```
[root@docker-ambari tmp]# ll -h /var/log/ambari-agent/
total 2.5G
-rw-r--r-- 1 root root 2.5G Oct 23 08:32 ambari-agent.log
-rw-r--r-- 1 root root  48M Oct 20 14:51 ambari-agent.log.1
-rw-r--r-- 1 root root 8.2M Oct 23 08:32 ambari-agent.out
```
Thanks

**Comment by martonsereg** [comment]
Sorry, I didn't have time to look into it yet, I'll let you know if I find something.
Until then I suggest to empty the logfiles manually if they eat up too much space.

On 23 Oct 2015 10:34 am, Alessandro Federico <notifications@github.com> wrote:

Any news about it? My logs are getting bigger

[root@docker-ambari tmp]# ll -h /var/log/ambari-agent/
total 2.5G
-rw-r--r-- 1 root root 2.5G Oct 23 08:32 ambari-agent.log
-rw-r--r-- 1 root root  48M Oct 20 14:51 ambari-agent.log.1
-rw-r--r-- 1 root root 8.2M Oct 23 08:32 ambari-agent.out


Thanks

-

**Comment by martonsereg** [comment]
Can you check your `/etc/ambari-agent/conf/ambari-agent.ini`file? The loglevel under `[agent]` should be set to `INFO` by default. Starting the agent with the -v switch doesn't change it to `DEBUG` for me, but we'll remove the verbose switch in the next release, just in case.
Until then you can try to change the .ini file loglevel to INFO and restart the ambari-agents.

Regarding the log rotation it seems more like an Ambari issue than Cloudbreak. Please open an issue for Ambari if that is still a problem.

**Comment by afederic** [comment]
Yes, it is. 
```
[root@docker-ambari tmp]# grep loglevel /etc/ambari-agent/conf/ambari-agent.ini
;loglevel=(DEBUG/INFO)
loglevel=INFO
```
but I seems that running the agent with the -v switch enables the DEBUG mode.
Both the files log this
```
[root@docker-ambari tmp]# head /var/log/ambari-agent/ambari-agent.log.1
INFO 2015-10-20 12:17:01,571 main.py:70 - loglevel=logging.DEBUG
INFO 2015-10-20 12:17:01,571 main.py:70 - loglevel=logging.DEBUG
INFO 2015-10-20 12:17:01,635 DataCleaner.py:39 - Data cleanup thread started
INFO 2015-10-20 12:17:01,637 DataCleaner.py:120 - Data cleanup started
DEBUG 2015-10-20 12:17:01,637 DataCleaner.py:71 - Cleaning up inside directory /var/lib/ambari-agent/data

[root@docker-ambari tmp]# head  /var/log/ambari-agent/ambari-agent.log
INFO 2015-10-20 14:50:58,666 main.py:74 - loglevel=logging.INFO
INFO 2015-10-20 14:51:04,296 main.py:70 - loglevel=logging.DEBUG
INFO 2015-10-20 14:51:04,296 main.py:70 - loglevel=logging.DEBUG
INFO 2015-10-20 14:51:04,308 DataCleaner.py:39 - Data cleanup thread started
INFO 2015-10-20 14:51:04,312 DataCleaner.py:120 - Data cleanup started
DEBUG 2015-10-20 14:51:04,313 DataCleaner.py:71 - Cleaning up inside directory /var/lib/ambari-agent/data
```
Thanks
Ale

**Comment by martonsereg** [comment]
I've removed the verbose switch from the agent start: https://github.com/sequenceiq/docker-ambari/pull/86, the next Cloudbreak release will contain this change.

**Comment by afederic** [comment]
Thanks!
