### ISSUE TITLE
Fail to create cluster based on AWS

### ISSUE THREAD

**Issue by zouyu721** [sequenceiq/cloudbreak#1075]
Hi,

I try to setup a cluster on AWS with Cloudbreak UI. Followed the instruction, I've linked Cloudbreak to my aws account. I used hdp-spark-cluster with default settings, except Ambari repository configuration.

Here is the error:
10/28/2015 1:36:55 PM cluster - create failed: Ambari cluster could not be created. Reason: com.sequenceiq.cloudbreak.service.cluster.AmbariOperationFailedException: Ambari Blueprint could not be added: The component 'ZEPPELIN_MASTER' in host group 'host_group_master_2' is not valid for the specified stack

Here is my Ambari repository configuration:
stack='HDP', 
version='2.3', 
os='redhat6', 
stackRepoId='HDP-2.3', 
utilsRepoId='HDP-UTILS-1.1.0.20', 
stackBaseURL='http://public-repo-1.hortonworks.com/ambari/centos6/2.x/updates/2.1.0', utilsBaseURL='http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.20/repos/centos6', verify=true

Thanks,

**Comment by keyki** [comment]
It's a bug in Cloudbreak if you explicitly specify the HDP repo it will use the wrong docker container, but it has been fixed on the master so you have 3 options:
* Go to the UI click on the spark blueprint copy & edit and remove the ZEPPELIN_MASTER from it
* do not specify any HDP repo and it will use the latest available for that stack
* in your CBD Profile put export CB_DOCKER_CONTAINER_AMBARI="sequenceiq/ambari-warmup:2.1.0-consul";

**Comment by zouyu721** [comment]
Thanks! I used 2nd option and it worked.
