### ISSUE TITLE
HDP repo version not selectable

### ISSUE THREAD

**Issue by jyates** [sequenceiq/cloudbreak#1095]
I'm not sure if this belongs in uluwatu or here or the shell, but I can't seem to change the selected HDP respository type (e.g. redhat 6 -> redhat 7). I can specify a different repo location in the configuration for the redhat 7, but this should be selectable (its greyed out).

This is an immediate issue b/c the default AMIs - at least for AWS and Azure - seem to be centOS7.1, but all I can select is the redhat6 repository. 

Maybe part of the solution comes in being able to specify the repository location in the blueprint (maybe needs pushed up to ambari community) or the expected OS type of the instance and dynamically selecting the right one.

**Comment by jyates** [comment]
Well, actually they say:
```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.1 (Maipo)
```

**Comment by keyki** [comment]
Hi,

The reason you cannot choose a different OS as the host is indeed redhat 7.1, but we're running Ambari in docker containers which is centos 6.6 [ref](https://github.com/sequenceiq/docker-ambari/blob/master/ambari-server/Dockerfile#L2)

**Comment by jyates** [comment]
Ah, great. Thanks @keyki! Makes sense.
