### ISSUE TITLE
failed to start due to table error

### ISSUE THREAD

**Issue by ylvmw** [sequenceiq/cloudbreak#1181]
Hi,

When I started the services with the latest cbd, the cloudbreak service would fail due to the table error, please see the error below:

Caused by: org.hibernate.HibernateException: Missing column: DTYPE in public.credential
at org.hibernate.mapping.Table.validateColumns(Table.java:365)
at org.hibernate.cfg.Configuration.validateSchema(Configuration.java:1336)
at org.hibernate.tool.hbm2ddl.SchemaValidator.validate(SchemaValidator.java:155)
at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:525)

cbd version: 1.1.0-master-c3a5b31
cloudbreak images:
```
REPOSITORY                      TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
gliderlabs/consul-server        0.5                 f27a3420f49e        9 hours ago         37.17 MB
sequenceiq/cloudbreak           1.1.0-rc.43         e002ecd13a05        2 days ago          453.9 MB
alpine                          latest              d6ead20d5571        7 days ago          5.253 MB
sequenceiq/uluwatu-bin          1.1.0-rc.20         ccc3c17a03aa        13 days ago         81.48 MB
sequenceiq/pcdb                 1.0.0-rc.3          c3468ea88156        4 weeks ago         218.2 MB
sequenceiq/cbdb                 1.1.0-rc.28         3b7a1e970ab3        4 weeks ago         218.4 MB
sequenceiq/periscope            1.0.0-rc.3          168ed3b04927        4 weeks ago         420.5 MB
sequenceiq/uaadb                v2.7.1              b694f25db9d7        5 weeks ago         269.9 MB
sequenceiq/sultans-bin          1.1.0-rc.5          4dbf76ec9eb7        5 weeks ago         59.05 MB
sequenceiq/uaa                  2.7.1               430763923372        5 weeks ago         752.4 MB
sequenceiq/socat                1.0.0               5de45ef55f6f        10 weeks ago        140.5 MB
sequenceiq/mybatis-migrations   1.0.0               a003ee3746fe        3 months ago        347.2 MB
gliderlabs/logspout             master              5e0980f79b63        3 months ago        14.75 MB
gliderlabs/registrator          v5                  9d2336648696        4 months ago        20.6 MB
ehazlett/cert-tool              0.0.3               d665a9f52b35        7 months ago        6.393 MB 
```
could you take a look of it?

**Comment by lalyos** [comment]
hi @ylvmw 

When `cbd start` is issued first it runs migration on all 3 databases (cbdb/pcdb/uaadb) it should be able to make all the changes needed for the actual versions.

Could you please try a `cbd migrate` and see if it succeeds, or reports some error?

**Comment by lalyos** [comment]
Or, if something is really messed up, and you have no running clusters, you can just delete all the databases with `cbd delete`. If the databases are deleted `cbd start` will recreate them.

**Comment by ylvmw** [comment]
Great! ```cbd delete``` works. 

Thanks!

**Comment by lalyos** [comment]
cool. just curious: did you try `cbd migrate`, did it report any issue?

**Comment by ylvmw** [comment]
yes, I tried it. Here is the log:
```
./cbd migrate
generating docker-compose.yml
Migration SUCCESS: cbdb up
Migration SUCCESS: cbdb pending
Migration SUCCESS: pcdb up
Migration SUCCESS: pcdb pending
Migration SUCCESS: uaadb up
Migration SUCCESS: uaadb pending
```
but it took no effect.
