### ISSUE TITLE
Support disks up to 2 TB for AWS

### ISSUE THREAD

**Issue by promiseu77** [sequenceiq/cloudbreak#1206]
For VMs in AWS, 
AWS supports up to 2TB Volume size on OS disk but Cloudbreak only allows to create 1TB volume size for all cloud providers. Also Cloudbreak supports up to 12 disks maximum.

This is not sufficient for future needs so please consider supporting more disk and volume size.

Please consider supporting up to 24 disks or more with 2-TB of capacity each. 

Thanks

**Comment by Beelal** [comment]
+1

**Comment by nsteinmetz** [comment]
Hi there,

As we expect to have more than 1TB data too, if we initiate the cluster with a 1TB storage volume and then expend it to our needs from the AWS console, is there an issue with that ? Of course, it can't apply for autoscaling nodes only for "static" ones.

It's the only workaround I see.

Thanks,
Nicolas

**Comment by martonsereg** [comment]
Hi,

Cloudbreak release 1.2.1 already supports more than 12 disks and more than 1T disks from the UI for *ephemeral volumes*, like for a d2.8xlarge instance with 24 attached 2T disks.
For EBS volumes, more than 12 disks that are larger than 1T is supported from the cloudbreak shell, but not from the UI. You can start cloudbreak-shell with `cbd util cloudbreak-shell` and create a template from there, then use the template from the UI.
Also please note that *EBS magnetic volumes* cannot be larger than 1T, it's a limitation by AWS.

Marton

**Comment by nsteinmetz** [comment]
Hi @martonsereg 

Ok, understood.

Will have a look into cb-shell then :)

Thanks !
Nicolas
