### ISSUE TITLE
Mismatching validation and error message on volume size

### ISSUE THREAD

**Issue by promiseu77** [sequenceiq/cloudbreak#1207]
The validation of volume size allows 10 to 1000 (GB). Either the validation should allow up to 1024-GB volumes, or the error message should instead say: "Volume size must be between 10 and 1000". 

But Error message is "Volume size must be between 10 and 1024" at current version. (1.1.0)

**Comment by doktoric** [comment]
Thanks for reporting this,
I will raise a bug and fix it in the next release.

**Comment by doktoric** [comment]
fixed on master
