### ISSUE TITLE
AMBARI_CLUSTER_STARTING failed during bootstrap a cluster

### ISSUE THREAD

**Issue by ylvmw** [sequenceiq/cloudbreak#1226]
Hi,

I just met the issue that ambari failed to start during bootstrapping a cluster. Could you help to take a look?

The log:
```
Ambari health check failed. Bad Gateway Trying again in next polling interval.
```
The log from ngnix container:
```
[error] 6#6: *287 connect() failed (111: Connection refused) while connecting to upstream, client: *.*.*.*, server: , request: "GET /api/v1/check HTTP/1.1", upstream: "http://127.0.0.1:8080/api/v1/check", host: "*.*.*.*:443"
``` 

The log from ambari container:
```
Using python  /usr/bin/python2.6
Starting ambari-server
WARNING: The hostname was not found in the reverse DNS lookup. This may result in incorrect behavior. Please check the DNS setup and fix the issue.
Ambari Server running with administrator privileges.
Organizing resource files at /var/lib/ambari-server/resources...
Server PID at: /var/run/ambari-server/ambari-server.pid
Server out at: /var/log/ambari-server/ambari-server.out
Server log at: /var/log/ambari-server/ambari-server.log
Waiting for server start....................
Ambari Server 'start' completed successfully.
+ sleep 30
++ grep 8080
++ netstat -tulpn
+ '[' -z '' ']'
+ ambari-server start
```

**Comment by ylvmw** [comment]
It seemed that the Ambari container didn't listen to the 8080 port.

**Comment by biharitomi** [comment]
Hi,
As @keyki asked you in an other issue [https://github.com/sequenceiq/docker-ambari/issues/106#issuecomment-173872033].
Could you please check the ambari server logs in the '/hadoopfs/fs1/logs/ambari-server/ambari-server.log' file on the gateway vm?

**Comment by matyix** [comment]
What is your environment you are using? Which Linux distribution and version and which cloud provider? It seams that (you don't need to post to all repositories the same problem, btw) that you have DNS problems on your env.
This container is supported, certified and in production on AWS, Azure, GCP and OS (Kilo and Juno) and it works on all these env. We can't control and don't know what did you change but WmVare (as it seams that you are using) it's not supported. Converting the OS image to a Vmdk is not going to result in a working image out of the box - so if you want to get this working first try to get the networking working on your VmWare environment.

The Ambari image is using NET=HOST which means that all the networking is inherited from the HOST, thus if you don't get it right it will not work. This is not a Cloudbreak issue at all.

I suggest first try to get any basic container e.g. Tomcat starting with net=host and get it working in your environment (being able to resolve the address, routing, and reverse lookups) - than you can jump to the Ambari image.
