### ISSUE TITLE
Use of direct-lvm instead of loop-lvm within containers ?

### ISSUE THREAD

**Issue by nsteinmetz** [sequenceiq/cloudbreak#1231]
Hi,

First, thanks to build cloudbreak as it allowed us to create our first hadoop clusters in a few clicks.

However, now that we dive more into the sublayers, I noticed that:
* Docker use devicemapper with ``loop-lvm`` mode
* Docker itself [does not recommend ``loop-lvm`` mode](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#other-device-mapper-performance-considerations) for production but ``direct-lvm`` instead.

Is there a way to use ``direct-lvm`` in a cloudbreak context ?

Otherwise, I saw you [had issues with "overlayfs" and fall back to devicemapper](https://github.com/sequenceiq/cloudbreak/issues/854#issuecomment-129946018). Any progress on this even if on our side, it would mean to drop CentOS/RHEL for Debian/Ubuntu.

Thanks,
Nicolas

**Comment by biharitomi** [comment]
Hi @nsteinmetz ,

We still use CentOS/RHEL and the `loop-lvm` and do not experience production issues with that. We have investigated the `direct-lvm` and it worked fine for us, but not too easy to integrate it in our stack.
I think you have to create your own image to use direct-lvm, so there is no easy way that configures it through Cloudbreak.

Br,
Tamas

**Comment by nsteinmetz** [comment]
Ok thanks ; and for the overlayfs, is it available for ex with Debian/Ubuntu or do you use only devicemapper for all linux distributions so far ?

**Comment by biharitomi** [comment]
Hi,

We only use and support CentOS/RHEL distributions. Definitely the overlayfs would work on Debian/Ubuntu.

**Comment by nsteinmetz** [comment]
Oh indeed, I mixed the OS supported by cloudbreak and the one by HDP.
