### ISSUE TITLE
Is there a way to change the dm.basesize ?

### ISSUE THREAD

**Issue by nsteinmetz** [sequenceiq/cloudbreak#1232]
Hi,

Is there a way to refine/define/override  the ``dm.basesize`` if we want to allow containers larger than 30GB for our clusters ?

Thanks,
Nicolas

**Comment by biharitomi** [comment]
Hi @nsteinmetz ,

The `dm.basesize` option is not configurable through Cloudbreak. Our image burning mechanism configures the systemd Docker service with 30G.
What would you like to add to the containers that requires the mentioned huge size?

**Comment by nsteinmetz** [comment]
Hi,

It's just that a dev for what I understood launched some spark jobs with ``nohup`` and thus logs were not rotated correctly and alsmot filled the 30G.

I was thinking of extending the image or add volumes to container to ease management.  I saw there is some logrotate container too and need to see how they work to use this feature instead.

**Comment by biharitomi** [comment]
Hi,

We use attached disks to store logs and other heavy data, these disks are attached to the container as a volume. (As you can find Ambari agent logs on the host in the `/hadoopfs/fs1/`... folder. The attached disks from the vm are mounted to these folders and added to the Ambari agent container as volumes) If you started the cluster with Cloudbreak, there should be at least 1 attached disk.
There is no way to add more volumes to a running container using Cloudbreak yet.

Br,
Tamas

**Comment by nsteinmetz** [comment]
Thanks, I'll share this info with the dev team and work with this in mind.
