### ISSUE TITLE
Is it possible do declare owr own docker registry within cloudbreak ?

### ISSUE THREAD

**Issue by nsteinmetz** [sequenceiq/cloudbreak#1235]
Hi,

Is it possible to declare in cloudbreak our custom docker registry so that images are pulled from this registry instead of docker hub ? Or is the only way to customise a host about to use cloudbreak recipes ?

Thanks,
Nicolas

**Comment by doktoric** [comment]
Hi @nsteinmetz 
I just wondering why you need own docker registry (what is the use case)? Do you have any custom image?
Our cloud images contains every docker image which needed for the cloudbreak and currently we are not supporting the custom repositories.
br, 
R

**Comment by nsteinmetz** [comment]
Hi,

There are a few potential use cases:
* We try to avoid to depend from internet resources or more precisely let servers access to internet without limitations (even if they are in a VPC). In an ideal world from our security officier point of view:
** our internet gateway should be shut down and we should only access via the vpn gateway linked to our infrastructure
** access to internet resources should go trought a filtering proxy
* If we need to customise images, we want that our custom images are used instead of the public ones. 
** customisation could be for ex to register the vm against our monitoring platform ; this client could be either a new container by itself or the modification of an existing image to add this feature.
** maybe some developments will require to deploy a few settings or app that would require customisation
** for ex, we would like to use also Hue, we may need another container for that
** for ex, our dev started manually spark jobs by connecting to the container and starting spark. If we autoscale, this can't be done this way. So we may need some extra entrypoint for ex.

We're still in the early stage of our implementation and I try to match our usual requirements with the new use cases around big data and also to see how we can extend the platform as it is provided to match some needs.

**Comment by nsteinmetz** [comment]
Answer was given as part à #1233 ; no support of custom registry so far.
