### ISSUE TITLE
UAA_DOMAIN to enable cloudbreak-shell

### ISSUE THREAD

**Issue by nsteinmetz** [sequenceiq/cloudbreak#1268]
Hi,

So from #1260, I have:

```
export PUBLIC_IP=cloudbreak.subdomain.company.com
export ULU_HOST_ADDRESS=http://cloudbreak.subdomain.company.com/
export ULU_OAUTH_REDIRECT_URI=http://cloudbreak.subdomain.company.com/authorize
export ULU_SULTANS_ADDRESS=http://cloudbreak-oauth.subdomain.company.com
export CB_HOST_ADDR=http://cloudbreak-api.subdomain.company.com
export UAA_ZONE_DOMAIN=cloudbreak-identity.subdomain.company.com
```

But [from the doc and UAA domain](http://sequenceiq.com/cloudbreak-docs/latest/configuration/#available-configurations), I'm a little bit sceptical about my setting.

From the docs, I would think that ``UAA_ZONE_DOMAIN`` is more ``subdomain.company.com`` but the issue is that I don't have a vhost at this level.  

From [previous comment](https://github.com/sequenceiq/cloudbreak/issues/1260#issuecomment-178599232) of @biharitomi:

    if you would like to use cloudbreak-shell later the identity server also needs a subdomain, 
    and then check the 'Access from custom subdomain' section of the doc: 
    http://sequenceiq.com/cloudbreak-docs/latest/configuration/#available-configurations

So mixing both, I would more expect having something like:

```
export UAA_ZONE_DOMAIN=subdomain.company.com
export SOME_VARIABLE_REGARDING_IDENTITY=cloudbreak-identity.subdomain.company.com
```

So far, my vhost for ``cloudbreak-identity.subdomain.company.com``  is a reverse-proxy to ``http://localhost:8089/``

What did I miss ?

Thanks,
Nicolas

**Comment by biharitomi** [comment]
Hi @nsteinmetz ,

You should add only the `UAA_ZONE_DOMAIN` variable to your Profile, that's value should be the domain of your identity server. In one of our environment it looks like `export UAA_ZONE_DOMAIN=identity.sequenceiq.com`. This variable is necessary for UAA to requests that has host with value 'identity.sequenceiq.com' should be handled by the default UAA zone provider as requests that comes from local network.

Br,
Tamas

**Comment by nsteinmetz** [comment]
hi @biharitomi 

Ok, understood.

It's the sample in the doc which makes me confused at it implies a sort of hierarchy at a DNS level (the way I understood zone)

     If the standard UAA responds to https://uaa.10.244.0.34.xip.io a zone on this UAA would be 
     accessed through https://testzone1.uaa.10.244.0.34.xip.io.

I thought:
* ``uaa.10.244.0.34.xip.io`` was the "parent" zone
* ``testzone1.uaa.10.244.0.34.xip.io`` was a child entry of the parent zone

And so that each cloudbreak entry should be a child of the parent zone.

So with your answer, I understand that my settings are correct and that I can use chouldbreak-shell.

I quickly tested it yesterday but as no credentials were listed (I exepcted to use the same as in the UI without doing anything), I thought I made something wrong with my ``Profile`` settings

Will test it deeper this afternoon.

Thanks,
Nicolas

**Comment by nsteinmetz** [comment]
Ok my bad, I confused ``credentials list`` vs ``credentials show`` ; works as expected.

Thanks,
Nicolas

**Comment by biharitomi** [comment]
Hi @nsteinmetz ,

Good to hear it works!
We will update the docs, I copied those sentences from the UAA documentation, but the UAA code needed to be checked to create a working solution for our deployment after the UAA zones had came in the UAA domain.

Br,
Tamas
