### ISSUE TITLE
Invalid node count on instance group host_group_master_3; Cluster creation failed'

### ISSUE THREAD

**Issue by shar101** [sequenceiq/cloudbreak#1298]
Hi,

I am using Cloubreak 1.1 to install a small hdp-small-default on Google Cloud. The bluprint is found b default in the cloudbreak UI under manage blueprints. No customization was done to test out the cluster creation. 

Below are some relevant logs. Please let me know how to resolve the issue 

/cbreak_cloudbreak_1 | 2016-02-11 18:37:10,934 [reactorDispatcher-88] accept:38 ^[[34mINFO ^[[0;39m c.s.c.s.e.CloudbreakEventHandler - [owner:undefined] [type:CLOUDBREAKEVENTDATA] [id:undefined] [name:undefined] Sending notification with data: CloudbreakEvent{id=7, eventType='UPDATE_IN_PROGRESS', eventTimestamp=Thu Feb 11 18:37:10 UTC 2016, eventMessage='Bootstrap failed on 6 nodes. These nodes will be terminated', owner='4ae73527-6f81-41da-b011-7b08089d4ce1', account='seq1234567', cloud='GCP', region='US_CENTRAL1_F', blueprintName='hdp-small-default', instanceGroup='null', blueprintId=1, stackId=1}

/cbreak_uluwatu_1 | ^[[0mPOST /notifications ^[[32m200 ^[[0m0.862 ms - -^[[0m

/cbreak_cloudbreak_1 | 2016-02-11 18:37:11,001 [reactorDispatcher-89] fireEventAndLog:627 ^[[39mDEBUG^[[0;39m c.s.c.c.f.s.SimpleStackFacade - [owner:4ae73527-6f81-41da-b011-7b08089d4ce1] [type:STACK] [id:1] [name:hdp-cb-poc1] STACK_INFRASTRUCTURE_CREATE_FAILED [STACK_FLOW_STEP]. Context: ProvisioningContext{, setupProperties={}, userDataParams={}, resources=[], coreInstanceMetaData=[], ambariIp='null'}

/cbreak_cloudbreak_1 | 2016-02-11 18:37:11,002 [reactorDispatcher-89] fireCloudbreakEvent:51 ^[[34mINFO ^[[0;39m c.s.c.s.e.DefaultCloudbreakEventService - [owner:4ae73527-6f81-41da-b011-7b08089d4ce1] [type:STACK] [id:1] [name:hdp-cb-poc1] Firing Cloudbreak event: CloudbreakEventData{entityId=1, eventType='CREATE_FAILED', eventMessage='Infrastructure creation failed. Reason: com.sequenceiq.cloudbreak.core.CloudbreakException: com.sequenceiq.cloudbreak.orchestrator.exception.CloudbreakOrchestratorFailedException: Invalid node count on instance group host_group_master_3; Cluster creation failed'}

/cbreak_cloudbreak_1 | 2016-02-11 18:37:11,003 [reactorDispatcher-89] handleStackCreationFailure:266 ^[[39mDEBUG^[[0;39m c.s.c.c.f.s.SimpleFlowFacade - [owner:4ae73527-6f81-41da-b011-7b08089d4ce1] [type:STACK] [id:1] [name:hdp-cb-poc1] Stack creation failure handled.

/cbreak_cloudbreak_1 | 2016-02-11 18:37:11,003 [reactorDispatcher-89] execute:22 ^[[34mINFO ^[[0;39m c.s.c.c.f.h.StackCreationFailureHandler - [owner:4ae73527-6f81-41da-b011-7b08089d4ce1] [type:STACK] [id:1] [name:hdp-cb-poc1] Stack creation failure  handled. Context: ProvisioningContext{, setupProperties={}, userDataParams={}, resources=[], coreInstanceMetaData=[], ambariIp='null'}

/cbreak_cloudbreak_1 | 2016-02-11 18:37:11,003 [reactorDispatcher-89] assemblePayload:120 ^[[34mINFO ^[[0;39m c.s.c.c.f.AbstractFlowHandler - [owner:4ae73527-6f81-41da-b011-7b08089d4ce1] [type:STACK] [id:1] [name:hdp-cb-poc1] Default service result decoration for class com.sequenceiq.cloudbreak.core.flow.handlers.StackCreationFailureHandler

/cbreak_cloudbreak_1 | 2016-02-11 18:37:11,003 [reactorDispatcher-89] transitionForClass:39 ^[[39mDEBUG^[[0;39m c.s.c.c.f.s.SimpleTransitionKeyService - [owner:4ae73527-6f81-41da-b011-7b08089d4ce1] [type:STACK] [id:1] [name:hdp-cb-poc1] Retrieving transition for class: class com.sequenceiq.cloudbreak.core.flow.handlers.StackCreationFailureHandler

**Comment by martonsereg** [comment]
Hi,

"Bootstrap failed on 6 nodes" -> it means that Cloudbreak failed to bootstrap the Consul/Swarm cluster on the nodes for some reason that's needed to deploy the ambari containers. We'll need some more information to debug it - please SSH onto the cloudbreak-gateway node of your cluster if still running, check the docker containers with `docker ps -a`, look for a container named `munchausen-<timestamp>` and send its logs (`docker logs -f <container-id>`) to us.

**Comment by martonsereg** [comment]
Please also help with the following:

- after Cloudbreak fails, ssh to the gateway node

- check your swarm container's version with the docker images command (I think it's 0.4.0)

- check the line in the munchausen logs that looks something like this: `"Creating swarm manager container with discovery parameter: 10.0.0.5:2376,10.0.0.3:2376,10.0.0.2:2376,10.0.0.4:2376"`

- copy the ip addresses and start a new swarm manager with this command (change the ips and the swarm version if different):

`docker run --name swarm-debug -p 3375:3376 -d swarm:0.4.0 manage -H tcp://0.0.0.0:3376 10.0.0.5:2376,10.0.0.3:2376,10.0.0.2:2376,10.0.0.4:2376`

- check the logs of the newly started swarm manager with

`docker logs swarm-debug`

- check if the nodes got registered successfully (please send us the result of both commands):

`docker  -H tcp://127.0.0.1:3375 info`
`curl http://127.0.0.1:3375/info | jq .`

**Comment by shar101** [comment]
It appears the munchausen container has exited 28 hours ago.
5ab67f3b74da        sequenceiq/munchausen:0.5.5       "/bin/swarm-bootstrap"   28 hours ago        Exited (1) 28 hours ago                        munchausen1455213295773

**Comment by martonsereg** [comment]
It is expected, but you can still check out the logs of the exited docker container with `docker logs -f 5ab67f3b74da`

**Comment by shar101** [comment]
This is what I find in the logs regarding creating swarm manager
time="2016-02-11T17:55:03Z" level=debug msg="[containerhandler] Creating swarm manager container with discovery parameter: 10.0.0.7:2376,10.
0.0.5:2376,10.0.0.3:2376,10.0.0.2:2376,10.0.0.4:2376,10.0.0.6:2376"

Copied IP addresses from the previous command and restarting swarm manager now
docker run --name swarm-debug -p 3375:3376 -d swarm:0.4.0 manage -H tcp://0.0.0.0:2376 10.0.0.7:2376,10.0.0.5:2376,10.0.0.3:2376,10.0.0.2:2376,10.0.0.4:2376,10.0.0.6:2376
Error response from daemon: Conflict. The name "swarm-debug" is already in use by container 1b528af48e2e. You have to delete (or rename) that container to be able to reuse that name.
There is contention on the "swarm-debug" name. Should I rename it to something else or somehow delete the container?

**Comment by shar101** [comment]
It appears its the swarm-bootstram container that has exited. swarm-debug has been up 2 days ago

CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                  PORTS                            
  NAMES
1b528af48e2e        swarm:0.4.0                       "/swarm manage -H tcp"   11 minutes ago      Up 11 minutes           2375/tcp, 0.0.0.0:3375->3376/tcp 
  swarm-debug
7cfc01427f0e        swarm:0.4.0                       "/swarm --debug manag"   2 days ago          Up 2 days               2375/tcp, 3376/tcp               
  tmp-swarm-manager
5ab67f3b74da        sequenceiq/munchausen:0.5.5       "/bin/swarm-bootstrap"   2 days ago          Exited (1) 2 days ago                                    
  munchausen1455213295773
1455c4cb86a5        sequenceiq/cb-gateway-nginx:0.3   "nginx -g 'daemon off"   2 days ago          Up 2 days                                                
  gateway

**Comment by shar101** [comment]
docker logs swarm-debug 

root@hdpcbpoc1-cbgateway-0-20160211175101 akash_sharma]# docker logs swarm-debug
time="2016-02-13T21:25:51Z" level=info msg="Listening for HTTP" addr="0.0.0.0:2376" proto=tcp 
time="2016-02-13T21:25:51Z" level=error msg="Get http://10.0.0.2:23/v1.15/info: dial tcp 10.0.0.2:23: connection refused" 
time="2016-02-13T21:25:52Z" level=info msg="Registered Engine hdpcbpoc1-hostgroupmaster2-3-20160211175255 at 10.0.0.5:2376" 
time="2016-02-13T21:25:52Z" level=error msg="ID duplicated. EWKX:W4UE:7JKK:PV2I:ODEA:2IQO:PD5K:LJ2K:YHMO:NZH5:S3ND:6C7H shared by 10.0.0.5:2376 and 10.0.0.7:2
376" 
time="2016-02-13T21:25:52Z" level=error msg="ID duplicated. EWKX:W4UE:7JKK:PV2I:ODEA:2IQO:PD5K:LJ2K:YHMO:NZH5:S3ND:6C7H shared by 10.0.0.5:2376 and 10.0.0.3:2
376"

**Comment by doktoric** [comment]
Hi @shar101 

You can eliminate the problem on this way
Define cloudbreak version in your profile with put this line into your Profile file: 
​```export DOCKER_TAG_CLOUDBREAK=1.1.0-rc.23```

and after that type these commands:

```cbd kill```
```cbd regenerate```
```cbd start```
Br,

Richard
