### ISSUE TITLE
AWS Instances M4Large & M4XLarge are not available in the AWS Instance type list 

### ISSUE THREAD

**Issue by nsteinmetz** [sequenceiq/cloudbreak#1300]
Hi,

We use CB 1.1 so far.

These instances are listed in the java code (https://github.com/sequenceiq/cloudbreak/blob/2cdd524968d3798753f02e10422610a8e2e07b60/cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsInstanceType.java) but not in the Cloudbreak UI. I can't see if it's a post 1.1 update or not.

```
    M4Large("m4.large", meta(0, "")),
    M4Xlarge("m4.xlarge", meta(0, "")),
```

In CB-shell, it would be someting like below to add them in the UI :

```
template create --EC2 --name M4Large --description M4Large --instanceType M4Large
template create --EC2 --name M4Xlarge --description M4Large --instanceType M4Xlarge
```

Thanks,
Nicolas

**Comment by martonsereg** [comment]
Hi Nicolas,

thanks for reporting, the new instance types will be available in 1.2, we already have an internal JIRA about it.

Marton

**Comment by nsteinmetz** [comment]
Hi @martonsereg 

Is there a way so to create them in the meantime or must I wait for 1.2 release (any ETA ?)

Thanks,
Nicolas

**Comment by martonsereg** [comment]
I'm afraid you'll need to wait for 1.2, it is not in the backend code in 1.1.
I can't tell you an exact release date yet, but you can expect it in the following few weeks.

**Comment by nsteinmetz** [comment]
Ok thanks ; will use another vm profile in the meantime.
