### ISSUE TITLE
cloudbreak-shell : interact with container from outside ?

### ISSUE THREAD

**Issue by nsteinmetz** [sequenceiq/cloudbreak#1311]
Hi,

I would like to start/stop dev environment based on crontab to save money.

Seems I can do it via cloudbreak-shell but I would like to automate it.

Is there a way to run the cloudbreak-shell container in a daemon mode and run commands against it via ``docker exec``

Or should I build a docker image that inherit from cloudbreakshell, run the commands for each use case ?

Thanks,
Nicolas

**Comment by nsteinmetz** [comment]
Hi,

Reading https://github.com/sequenceiq/cloudbreak/tree/master/shell#automate-the-process, I understand, that I could do

```
cbd util cloudbreak-shell --cmdline /path/to/script
```

With ``script`` being something like:

```
credential select --name <mycred>
stack select --id <mystack>
cluster stop
stack stop
```
and the same for start ?

**Comment by doktoric** [comment]
Hi @nsteinmetz 
If you want to automate the process and lets say you have file test-my-shell.sh then you can use file this way:
```
cat test-my-shell.sh|cbd util cloudbreak-shell-quiet
```

**Comment by nsteinmetz** [comment]
Hi @doktoric 

I'll try this way and let you know.

Thanks,
Nicolas

**Comment by doktoric** [comment]
Hi @nsteinmetz 
If the solution worked for you then please close the issue.

Br,
Richard

**Comment by nsteinmetz** [comment]
Hi,

I'll do more tests on this next week ; I'll close once I have my results.

**Comment by nsteinmetz** [comment]
Hi @doktoric 

Question about the ``cluster stop`` and ``stack stop`` : does the latter wait for the cluster to stop properly or should we add some sleep() in the script (but seems not supported by cb-shell).

Same for startup process by the way.

Thanks,
Nicolas

**Comment by doktoric** [comment]
Hi @nsteinmetz 

If you are doing cluster stop and after that immediately doing a stack stop then the stack will be ins STOP_REQUESTED status which means, when the cluster stopped successfully cloudbreak will trigger a stack stop. Same for start process.
Br, 
Richard

**Comment by nsteinmetz** [comment]
Ok, thanks for the confirmation - so it worked the way you mentionned.

Thanks !
Nicolas
