### ISSUE TITLE
Prevent docker & maybe some other packages to be updated to avoid breaking cluster hosts

### ISSUE THREAD

**Issue by nsteinmetz** [sequenceiq/cloudbreak#1320]
Hi,

On our staging envt, I had to install ElasticSearch & Kibana. As a consequence, I added the related rhel repo and did a `yum update` to take the repository into account. By mistake and without seeing that `docker` (and maybe other related packages) would be updated, I made the update. I  realised `docker`was upgraded but so far, platform was still working. I made the update on the "hostgroup_client_1" node only.

Later yesterday, I was testing the stop/start cluster & stack via `cloudbreak-shell` and noticed that ambari cluster failed to start correctly. EC2 instances were up and running, docker containers also but ambari was not accessible.

On cloudbreak side, it reported all my nodes except `cbgateway` were `unhealthy` with the `host_group_client1` node being second in the list after `cbgateway`. With my current knowledge of cloudbreak and ambari, I seems I had no choice except to terminate current cluster and restart one from scratch. I tried to terminate first only the `hostgroup_client1` node but it did nothing.

I didn't keep logs so I can't provide more details.

However, I think that the issue is related with the docker upgrade and/or the 7.0 to 7.1 rhel upgrade process. But I would think more the docker one as the upgrade was from docker 1.8.3 to docker 1.10.1 with all the backwards incompatibility issue it may have.

I don't know if you can manage it but if docker is the guilty component, it would be great that when you create an instance, you block the capacity to upgrade some packages on host side if it can break the system.

Based from [RHEL KN](https://access.redhat.com/solutions/10185), it would mean to add this in `/etc/yum.conf` ; see last line here for `kernel` and `redhat-release` packages:

```
[main]
cachedir=/var/cache/yum/$basearch/$releasever
keepcache=0
debuglevel=2
logfile=/var/log/yum.log
exclude=kernel* redhat-release*                           <==== 
```

Fortunately, the envt was empty so there is no loss (except time on my side) ; but I think it would be worth to manage it properly to avoid a more significant disaster. Not updating hosts isn't possible, even on an private LAN in my opinion.

**Comment by lalyos** [comment]
Thanks @nsteinmetz for reporting it. We haven't started to run full tests on docker 1.10. But we have already run into cents7.1 docker 1.10 installation/upgrade issue. 

Regarding the actual suggestion: This is one reason we put everything into containers, so that `yum install` or `yum update` is restricted to a container.

So i would rather suggest to use a containerized ELK stack. At leat on those host you are using for cloudbreak, try to go the pure containers path.

**Comment by nsteinmetz** [comment]
Hi @lalyos,

I agree using a container could be a solution but it's more a workaround as if a sysadmin enforce update on hosts, it would crash anyway. It does not solve the problem by itself.

**Comment by mhmxs** [comment]
Hi @nsteinmetz ,

Cloudbreak doesn't use Docker to provision Ambari any more. So in newer versions of Cloudbreak issue couldn't happen.
