### ISSUE TITLE
Allow dns resolution from containers to access external ressources

### ISSUE THREAD

**Issue by nsteinmetz** [sequenceiq/cloudbreak#1355]
Hi,

Nore sure if it's strictely related to Cloudbreak but my need is to access some internal ressources. So I need some DNS resolution. It works well at host level but fails at container level.

Within container, I can only resolve consul entries.

I could edit the ``/etc/hosts`` but as we have auto-scaling in mind, it can't work this way. Is there a way via cloudbreak (or via ambari ?) to manage this ?

I was thinking first to add a side container to provide dns resolution, but consul already binds port 53. So it's not possible.

I use CB 1.1.0 on AWS.

Thanks,
Nicolas

**Comment by nsteinmetz** [comment]
Hi,

Seems it's possible with consul and [recursors](https://www.consul.io/docs/agent/options.html#recursors) - what would be the best way to update consul conf with autoscaling in mind?

**Comment by lalyos** [comment]
Hi @nsteinmetz could ypu pleas ellaborate a bit more on :
> my need is to access some internal ressources. So I need some DNS resolution. It works well at host level but fails at container level.

What is your use-case? 
- You want to run some extra containers, and register them into Consul?
- You want to run something inside the ambari-containers?
- Where do you want to use the new dns entry?

**Comment by nsteinmetz** [comment]
Hi @lalyos 

Sorry, I'll try to be more precise:
* We deploy some spark jobs; so I put jar & conf file in ``/data/jars`` so that it's accessible both from host and containers.
* We need to access to kafka servers which are located on our confluent platform (ie outside of our HDP platform)
* To access our Kafka servers, we added in AWS a VM which acts as DNS forwarder so that I can resolve both internal DNS (ie on company lan) and public DNS

On host side, it works well. I can resolve both ``google.fr`` and ``kafka.company.lan``. However, within container, I don't have resolution for company lan. Only for consul entries and public dns.

At host level, in my ``/etc/resolv.conf``, it points only to the given DNS forwarder.

So I could "hack" a container to edit its ``/etc/hosts`` as this node is persistent. But with autoscaling in mind, I can't edith ``/etc/hosts`` each time ;)

**Comment by nsteinmetz** [comment]
Good news : we provided prod envt and for them we have the DNS resolution. We provided them after we set up this DNS forwarder. 

So our UAT envt was set up before and thus uses only public DNS. Is there a  way to change the DNS defined in consul for the whole cluster without rebuilding it ?

**Comment by lalyos** [comment]
@nsteinmetz I just realized that you are using 1.1.0. We fixed this issue since that.
We configure consul to use the name-server settings from the host.
Here is the code: https://github.com/sequenceiq/munchausen/blob/master/swarmboot/containerhandler.go#L49

We wiill release shortly 1.2.0. so any name resolvable on host will be available in containers.
I just tested it on our test deployment.

Until you can use the new release, you can rely on your `/etc/hosts` workaround.

**Comment by nsteinmetz** [comment]
Ok, thanks !

It works ; the only point is to edit in fact the ``/etc/hosts`` file of the host as it's "pasted" into the container.

I wondered why my edit in the container were not persistent after VM reboot. I found why.
