### ISSUE TITLE
Can't downscale to the original cluster size

### ISSUE THREAD

**Issue by mdiouf** [sequenceiq/cloudbreak#1357]
Hi all,
First of all, thanks guys cloudbreak is really a cool stuff!
We have cluster of 8 nodes created using cloudbreak. We have a group_slave_1 (our data nodes) and group_slave_2 (worker nodes with only Node manager and ambari metric inside). Our HDFS replication factor is 2 and we have 2 data nodes and 1 worker node.
We scale the worker node based on application pending alert. It's working, depending to our load, cloudbreak add worker nodes in group_slave_2. After load we was expecting going back to 1 worker nodes based on our downscale policy (-1 node). But it not the case, at 3 worker nodes we have an exception in log saying that the replication factor is 2 so the cluster can't downscale. So we have now 2 data nodes and 3 working nodes and not 2 data nodes and 1 working nodes (our original cluster configuration)
What are we doing wrong?
Regards

**Comment by keyki** [comment]
Hey,

Cloudbreak does not allow you to scale down your cluster below replication factor + 1 node, so in your case below 3. It's a safety feature as it can happen that there is not enough space to move the data. This behavior might change in the future.

**Comment by mdiouf** [comment]
Hi,
Thanks for your reply but let me explain again. For hdfs stuff we have a
dedicated group with 2 nodes inside. What we scale is another group for
worker with only node manager component in side. The initial size of the
cluster was 8 nodes  (2 data nodes fors hdfs and one workernode) after
scale we have know a cluster oh 11 nodes  (2 data nodes fors hdfs and 3
workernode). Why in the replication factor cloudbreak don't count the
original 2 data nodes ?
Regards

Le ven. 26 févr. 2016 08:33, Krisztian Horvath <notifications@github.com> a
écrit :

**Comment by keyki** [comment]
I see. It looks like it's a bug in cloudbreak and ignores the fact that the host group you're trying to downscale does not have datanode in it so basically it doesn't allow any host group to scale below 3 in your case. Here's the relevant code for this behavior: [decommission](https://github.com/sequenceiq/cloudbreak/blob/master/core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/AmbariDecommissioner.java#L206). Also if the RM's web port is open in the security group we check for the running applications and if those nodes have ApplicationMasters we exclude them from the decommission and can happen the same. 

I'll create a JIRA for it and get it fixed. Thanks. Any feedback is welcome.

**Comment by mdiouf** [comment]
You got it!
Looking at the code the problem in decommisionning is getting the global replication factor: dfs.replication.
I also try setting dfs.replication at host group level but it's not working too :
```
{
            "name": "host_group_slave_2",
            "configurations" : [
        {
          "hdfs-site" : {
            "dfs.replication" : "0"
          }
        }
      ],
            "components": [             
                {
                    "name": "NODEMANAGER"
                },
                {
                    "name": "METRICS_MONITOR"
                }
            ],
            "cardinality": "1"
        },

```
here the exception stack : 

`cbreak_cloudbreak_1 | 2016-02-26 09:47:05,666 [http-nio-8080-exec-7] clusterHostgroupAdjusmentChange:200 INFO  c.s.c.c.ClusterController - [owner:41c11a7e-46f5-4420-b830-94e0c795bebf] [type:STACK] [id:13] [name:testscale] Cluster host adjustment request received. Stack id: 13
/cbreak_cloudbreak_1 | 2016-02-26 09:47:14,675 [http-nio-8080-exec-7] verifyNodeCount:532 INFO  c.s.c.s.c.AmbariClusterService - [owner:41c11a7e-46f5-4420-b830-94e0c795bebf] [type:STACK] [id:13] [name:testscale] Cannot downscale: replication: 2, adjustment: -1, filtered host size: 2
/cbreak_cloudbreak_1 | 2016-02-26 09:47:14,677 [http-nio-8080-exec-7] badRequest:46 ERROR c.s.c.c.ExceptionControllerAdvice - [owner:cloudbreak] [type:cloudbreakLog] [id:undefined] [name:cb] There is not enough node to downscale. Check the replication factor and the ApplicationMaster occupation.
/cbreak_cloudbreak_1 | com.sequenceiq.cloudbreak.controller.BadRequestException: There is not enough node to downscale. Check the replication factor and the ApplicationMaster occupation.
/cbreak_cloudbreak_1 |  at com.sequenceiq.cloudbreak.service.cluster.AmbariClusterService.verifyNodeCount(AmbariClusterService.java:533) ~[cloudbreak.jar!/:na]
/cbreak_cloudbreak_1 |  at com.sequenceiq.cloudbreak.service.cluster.AmbariClusterService.collectDownscaleCandidates(AmbariClusterService.java:454) ~[cloudbreak.jar!/:na]
/cbreak_cloudbreak_1 |  at com.sequenceiq.cloudbreak.service.cluster.AmbariClusterService.updateHosts(AmbariClusterService.java:229) ~[cloudbreak.jar!/:na]
/cbreak_cloudbreak_1 |  at com.sequenceiq.cloudbreak.controller.ClusterController.clusterHostgroupAdjusmentChange(ClusterController.java:208) ~[cloudbreak.jar!/:na]
/cbreak_cloudbreak_1 |  at com.sequenceiq.cloudbreak.controller.ClusterController.updateCluster(ClusterController.java:186) ~[cloudbreak.jar!/:na]
/cbreak_cloudbreak_1 |  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
/cbreak_cloudbreak_1 |  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
/cbreak_cloudbreak_1 |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
/cbreak_cloudbreak_1 |  at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
/cbreak_cloudbreak_1 |  at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215) ~[spring-web-4.0.7.RELEASE.jar!/:4.0.7.RELEASE]
/cbreak_cloudbreak_1 |  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132) ~[spring-web-4.0.7.RELEASE.jar!/:4.0.7.RELEASE]
/cbreak_cloudbreak_1 |  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) ~[spring-webmvc-4.0.7.RELEASE.jar!/:4.0.7.RELEASE]
/cbreak_cloudbreak_1 |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:749) ~[spring-webmvc-4.0.7.RELEASE.jar!/:4.0.7.RELEASE]
/cbreak_cloudbreak_1 |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:689) ~[spring-webmvc-4.0.7.RELEASE.jar!/:4.0.7.RELEASE]
/cbreak_cloudbreak_1 |  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83) ~[spring-webmvc-4.0.7.RELEASE.jar!/:4.0.7.RELEASE]
/cbreak_cloudbreak_1 |  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938) ~[spring-webmvc-4.0.7.RELEASE.jar!/:4.0.7.RELEASE]
/cbreak_cloudbreak_1 |  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870) ~[spring-webmvc-4.0.7.RELEASE.jar!/:4.0.7.RELEASE]
/cbreak_cloudbreak_1 |  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961) [spring-webmvc-4.0.7.RELEASE.jar!/:4.0.7.RELEASE]
/cbreak_cloudbreak_1 |  at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:874) [spring-webmvc-4.0.7.RELEASE.jar!/:4.0.7.RELEASE]
/cbreak_cloudbreak_1 |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:710) [javaee-api-7.0.jar!/:na]
/cbreak_cloudbreak_1 |  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837) [spring-webmvc-4.0.7.RELEASE.jar!/:4.0.7.RELEASE]
/cbreak_cloudbreak_1 |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javaee-api-7.0.jar!/:na]
/cbreak_cloudbreak_1 |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [tomcat-embed-core-7.0.55.jar!/:7.0.55]
/cbreak_cloudbreak_1 |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.55.jar!/:7.0.55]
/cbreak_cloudbreak_1 |  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-7.0.55.jar!/:7.0.55]
/cbreak_cloudbreak_1 |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-embed-core-7.0.55.jar!/:7.0.55]
/cbreak_cloudbreak_1 |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.55.jar!/:7.0.55]
/cbreak_cloudbreak_1 |  at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110) [spring-boot-actuator-1.1.8.RELEASE.jar!/:1.1.8.RELEASE]
/cbreak_cloudbreak_1 |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.0.7.RELEASE.jar!/:4.0.7.RELEASE]
/cbreak_cloudbreak_1 |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-embed-core-7.0.55.jar!/:7.0.55]
/cbreak_cloudbreak_1 |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.55.jar!/:7.0.55]
/cbreak_cloudbreak_1 |  at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:280) [spring-boot-actuator-1.1.8.RELEASE.jar!/:1.1.8.RELEASE]
/cbreak_cloudbreak_1 |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.0.7.RELEASE.jar!/:4.0.7.RELEASE]
/cbreak_cloudbreak_1 |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-embed-core-7.0.55.jar!/:7.0.55]
/cbreak_cloudbreak_1 |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-embed-core-7.0.55.jar!/:7.0.55]
/cbr`

**Comment by keyki** [comment]
Yep, thanks for checking, we'll fix this.

**Comment by keyki** [comment]
This issue has been fixed and will be part of the next release https://github.com/sequenceiq/cloudbreak/commit/6823e693d646a57c589492b9104e0c4b94e38e8b
