### ISSUE TITLE
Not able to add nodes on slave group

### ISSUE THREAD

**Issue by Beelal** [sequenceiq/cloudbreak#1397]
I clicked on Add Nodes; selected host_group_slave_1; changed 1 to 3 to scale up nodes. Cloudbreak was able to add EC2 instances and volume but couldn't add those hosts in the cluster. Error:

com.sequenceiq.cloudbreak.service.CloudbreakServiceException: com.sequenceiq.ambari.client.AmbariConnectionException: Cannot connect to Ambari https://52.86.136.161:443/api/v1/

SSL is not enabled on Ambari. Where is cloudbreak getting the api url?

When I navigated the URL https://52.86.136.161:443/api/v1/ I got:

"400 Bad Request
No required SSL certificate was sent"

**Comment by mhmxs** [comment]
Hi @Beelal, first of all can i ask you which version of Cloudbreak do you use?

**Comment by Beelal** [comment]
1.1.0

**Comment by mhmxs** [comment]
What is see is the Ambari has a self signed/invalid certification. "SSL certificate problem: Invalid certificate chain".

- Is your cbd certs folder contains the right certs?
- When you start Cloudbreak with the deployer, do you see `Certificate added to default Java trust store with alias [cert].` or `WARNING: Failed to add $cert to trust store.` message in the log? You could check by executing `docker logs cbreak_cloudbreak_1`.
- Did you change Ambari passwords after Cloudbreak started the cluster?
- Could you please push Sync on the cluster, what's happen?
- Could you please catch the concrete exception in the Cloudbreak log?

This looks an interesting issue, because somehow Cloudbreak created the cluster, and without any change on the Ambari side, it can recreate the connection between Ambari anytime. So we haven't faced issue like this before.

**Comment by Beelal** [comment]
While I was typing answers to your questions I realized I did change Ambari password and that was it. Thank you so much for your help!!! My humble opinion would be to show error message starting 'password incorrect' if possible.

Now, I have another related question for you. Since I didn't know what was wrong I went ahead and terminated 2 new nodes in AWS but cloudbreak UI is adding those in the 'Number of nodes' count. I did the sync and it was successful but the count doesn't change. Is there a way to set the node count back to the original one?

Thanks again @mhmxs for your help!

**Comment by mhmxs** [comment]
Glad to hear it works again. About your suggestion. This kind of exception not means password problem all the time, so it's hard to predestine the real issue behind the error.

About the node count. So you terminated nodes on the Amazon UI, and Cloudbreak didn't decrement node count during sync? Am i right? Did you fix missing nodes in Ambari? On the happy flow if one or more nodes gone, Ambari mark them as unhealthy after a while. When you press sync button we ask Ambari for current nodes and we update our database Unhealthy nodes become terminate-able on the UI. I see a "node leak" here, if someone fixes missing nodes in Ambari we don't update node status in our database, so stay in healthy. I have to do some investigation on this.

**Comment by Beelal** [comment]
Those 2 nodes were never added in Ambari as cloudbreak failed to connect. So, there are no missing nodes in Ambari.

Cloudbreak was only able to create nodes on AWS. I terminated those nodes on AWS. Syncing is not updating count on cloudbreak UI.

**Comment by mhmxs** [comment]
Cloudbreak does node creation in two steps. First creates the instance on the cloud provider (which was success), and than installs Ambari and adds to the cluster (which failed). So new nodes must appear on the UI in UNUSED state and UNUSED nodes could terminate on the UI one by one. Could you please share a screenshot from your node list on the UI?

**Comment by Beelal** [comment]
![image](https://cloud.githubusercontent.com/assets/1430223/13613286/56c904bc-e520-11e5-80e4-0e773b85766c.png)

**Comment by mhmxs** [comment]
Cloudbreak has a similar view, please share that one with me too.

**Comment by Beelal** [comment]
ok so there are unused nodes showing up. Simply go ahead and terminate? Thanks.

![image](https://cloud.githubusercontent.com/assets/1430223/13616084/378cb672-e52d-11e5-98b6-54218c6b6ce9.png)

**Comment by Beelal** [comment]
Now after I terminate unused nodes, Hbase master and region servers are getting stopped.

**Comment by Beelal** [comment]
ok I have figured out what is stopping HBase. Anytime I enable Phoenix SQL through Ambari; HBase stops. HBase remains running if I disable Phoenix SQL.

Cloudbreak is not updating status though:
![image](https://cloud.githubusercontent.com/assets/1430223/13619938/dcb1816a-e540-11e5-968e-9a6edebf2213.png)

**Comment by mhmxs** [comment]
Interesting because those nodes were not member of cluster. Could you please share event log of the termination? At code level we ask Ambari to decommission if node has Ambari status. But in that case Ambari didn't know about those nodes, and Cloudbread had to know this.

**Comment by mhmxs** [comment]
Sync doesn't help?

**Comment by mhmxs** [comment]
Do you have Ambari problems? If yes, my suggestion is to fix Ambari issues first, and when everything is green there than you should try sync again.

**Comment by Beelal** [comment]
Everything is green in Ambari. Sync didn't help.

Event History
3/8/2016 3:03:15 PM sonacloud-hdp-alpha - available: Host [name: ip-10-0-134-242.node.dc1.consul] state has been updated to: HEALTHY
3/8/2016 3:03:15 PM sonacloud-hdp-alpha - available: Host [name: ip-10-0-92-47.node.dc1.consul] state has been updated to: HEALTHY
3/8/2016 3:03:19 PM sonacloud-hdp-alpha - unknown: Cloudbreak cluster state synchronized with Ambari: The cluster's state is up to date.
3/8/2016 3:04:16 PM sonacloud-hdp-alpha - unknown: Cloudbreak cluster state synchronized with Ambari: The cluster's state is up to date.
3/8/2016 3:05:15 PM sonacloud-hdp-alpha - unknown: Cloudbreak cluster state synchronized with Ambari: The cluster's state is up to date.
3/8/2016 3:10:03 PM sonacloud-hdp-alpha - unknown: Cloudbreak cluster state synchronized with Ambari: The cluster's state is up to date.
3/8/2016 3:19:30 PM sonacloud-hdp-alpha - unknown: Cloudbreak cluster state synchronized with Ambari: The cluster's state is up to date.
3/8/2016 7:29:45 PM sonacloud-hdp-alpha - update in progress: Terminating host: ip-10-0-141-208.node.dc1.consul from host group: host_group_slave_1
3/8/2016 7:29:51 PM sonacloud-hdp-alpha - update in progress: Terminating host: ip-10-0-141-209.node.dc1.consul from host group: host_group_slave_1

**Comment by mhmxs** [comment]
Something went really wrong. My suggestion is to update database manually on your own risk! So please log into the instance where deployer runs, and execute these two commands:

```
docker exec -it cbreak_cbdb_1 su postgres -c "echo \"UPDATE stack SET status = 'AVAILABLE' WHERE name = 'stack-name'\" | psql"
docker exec -it cbreak_cbdb_1 su postgres -c "echo \"UPDATE cluster SET status = 'AVAILABLE' WHERE name = 'cluster-name'\" | psql"
```

When you are done, you should try sync again.

**Comment by Beelal** [comment]
Thanks for the commands. I was able to see 'Add/Remove' Nodes button and healthy status for initial nodes after running the command and sync. Still terminate is not working for 2 nodes. Here is the event:

3/9/2016 1:30:21 PM sonacloud-hdp-alpha - update in progress: Terminating host: ip-10-0-141-208.node.dc1.consul from host group: host_group_slave_1

My guess is that cloudbreak is trying to terminate those 2 nodes from AWS and not coming out of that loop. Of course those 2 nodes doesn't exists in AWS anymore.

Is there a command to safely clean up those 2 nodes in cloudbreak database and bring hostgroup count back to the original nodes?

Thanks for your help!

**Comment by mhmxs** [comment]
Please back up your database!

`sudo docker exec -it cbreak_cbdb_1 su postgres -c "echo \"UPDATE instancemetadata SET instancestatus = 'TERMINATED', terminationdate = 1457516419639 WHERE id = ID\" | psql"`

I hope this should work.
