### ISSUE TITLE
Notifications sent to old ELB url and not new CB urls.

### ISSUE THREAD

**Issue by nsteinmetz** [sequenceiq/cloudbreak#1415]
Hi,

At the beginning of our usage of Cloudbreak, Ops team set up some ELB on AWS to access cloudbreak.

I did change the url to no longer need this elb and they were deleted on AWS side.

However, in the logs, I stiil see:

```
/cbreak_cloudbreak_1 | 2016-03-10 09:20:26,862 [taskScheduler-1] send:36 INFO  c.s.c.s.n.HttpNotificationSender - [owner:spring] [type:springLog] [id:] [name:] Could not send notification to the specified endpoint: 'http://cloudbreak-lb-2031496223.eu-west-1.elb.amazonaws.com/notifications' Cause: I/O error on POST request for "http://cloudbreak-lb-2031496223.eu-west-1.elb.amazonaws.com/notifications":cloudbreak-lb-2031496223.eu-west-1.elb.amazonaws.com; nested exception is java.net.UnknownHostException: cloudbreak-lb-2031496223.eu-west-1.elb.amazonaws.com
/cbreak_uluwatu_1 | POST /notifications 200 1.013 ms - -
```

In my ``Profile`` file, I have:

```
export PUBLIC_IP=cloudbreak.aws.company.com
export UAA_DEFAULT_USER_EMAIL=cloudbreak@company.com
export UAA_DEFAULT_USER_PW=xxx
export AWS_ACCESS_KEY_ID=xxx
export AWS_SECRET_ACCESS_KEY=xxx
export ULU_HOST_ADDRESS=http://cloudbreak.aws.company.com/
export ULU_OAUTH_REDIRECT_URI=http://cloudbreak.aws.company.com/authorize
export ULU_SULTANS_ADDRESS=http://cloudbreak-oauth.aws.company.com
export CB_HOST_ADDR=http://cloudbreak-api.aws.company.com
export UAA_ZONE_DOMAIN=cloudbreak-identity.aws.company.com
```

So I think there are some settings maybe in the database that keeps the old ELB url.

Is there a way to fix it ?

Thanks,
Nicolas

**Comment by biharitomi** [comment]
Hi @nsteinmetz ,

You are right, in the Cloudbreak database there is a table called 'subscription'. This table contains every clients that has ever subscribed to get notifications from Cloudbreak.
I am afraid the only way to resolve your issue is deleting the subscription from the Cloudbreak database manually.

Let me/us know if you could not create the necessary SQLs!

Br,
Tamas

**Comment by nsteinmetz** [comment]
Hi @biharitomi,

Just to be sure, in the ``cbdb`` container, I have:

```
postgres=# select * from subscription;
 id | clientid |                                 endpoint
----+----------+---------------------------------------------------------------------------
  1 | uluwatu  | http://cloudbreak-lb-2031496223.eu-west-1.elb.amazonaws.com/notifications
  2 | uluwatu  | http://cloudbreak.aws.company.com/notifications
(2 rows)
```

So I just need to delete the first line?

```
DELETE FROM subscriptions WHERE id = 1;
```

**Comment by biharitomi** [comment]
Yes, if you would like not to send more notifications to that address.

Br,
Tamas

**Comment by nsteinmetz** [comment]
Ok, thanks !

Just did it and logs are now cleaner :)
