### ISSUE TITLE
One node can't no more resolve DNS

### ISSUE THREAD

**Issue by mdiouf** [sequenceiq/cloudbreak#1440]
Hello,
After cluster reboot using Cloudbrout. One node lost heartbeat. Ambari-agent is up but have the following error:
WARNING 2016-03-23 19:53:46,769 main.py:291 - Unable to determine the IP address of the Ambari server 'ambari-8080.service.consul'
INFO 2016-03-23 19:53:46,769 NetUtil.py:59 - Connecting to https://ambari-8080.service.consul:8440/ca
WARNING 2016-03-23 19:54:06,784 NetUtil.py:82 - Failed to connect to https://ambari-8080.service.consul:8440/ca due to [Errno -3] Temporary failure in name resolution
WARNING 2016-03-23 19:54:06,785 NetUtil.py:105 - Server at https://ambari-8080.service.consul:8440 is not reachable, sleeping for 10 seconds...

Can't ping other nodes user consul dns.
In /etc/resolv.conf I've:
nameserver 172.17.42.1
search service.consul node.dc1.consul

the ping on 172.17.42.1 from this node is not working but work find for other nodes.
An issue?
Regards

**Comment by mdiouf** [comment]
I've more information.
172.17.42.1 is the cloudbreak instance.
[root@ip-10-0-87-134 ec2-user]# ping 172.17.42.1
PING 172.17.42.1 (172.17.42.1) 56(84) bytes of data.
From 172.17.0.1 icmp_seq=1 Destination Host Unreachable
From 172.17.0.1 icmp_seq=2 Destination Host Unreachable
From 172.17.0.1 icmp_seq=3 Destination Host Unreachable
From 172.17.0.1 icmp_seq=4 Destination Host Unreachable
From 172.17.0.1 icmp_seq=5 Destination Host Unreachable
From 172.17.0.1 icmp_seq=6 Destination Host Unreachable
From 172.17.0.1 icmp_seq=7 Destination Host Unreachable

Things was working perfectly since 4 month. This arrive after daily reboot.
Thanks

**Comment by lalyos** [comment]
hi @mdiouf the 2 IP addresses (172.17.0.1 and 172.17.42.1) are the ip of the bridge network docker uses by default. Docker changed this between two versions, if I recall correctly it was between 1.9 and 1.10.

Could you please give the information:
- which version of docker are you using?
- which version of cbd are you using?
- please run `cbd doctor` and copy the output.

**Comment by mdiouf** [comment]
Hi @lalyos 
here the versions:
[root@ip-172-31-7-61 cloudbreak-deployment]# **cbd doctor**
===> Deployer doctor: Checks your environment, and reports a diagnose.
ping 8.8.8.8 on host OK
ping github.com on host OK
ping 8.8.8.8 in container OK
ping github.com in container OK
local version:1.2.0
latest release:1.2.0
docker command: OK
docker client version: OK
docker server version: OK
[root@ip-172-31-7-61 cloudbreak-deployment]# **docker version**
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 06:06:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 06:06:01 UTC 2015
 OS/Arch:      linux/amd64
[root@ip-172-31-7-61 cloudbreak-deployment]#

**Comment by lalyos** [comment]
I see you have upgraded to cbd 1.2.0, thats great, but i can see that you are stil using docker 1.8.3.

I would recommend to upgrad docker as well? After that you shoud see `1.10.3`

Then you should restart cloudbreak:
```
cbd kill
cbd regenerate
cbd start
```

**Comment by mdiouf** [comment]
Ok. Have you any advice about upgrading docker in the context of cloudbreak?

2016-03-24 10:19 GMT+01:00 lalyos <notifications@github.com>:

> I see you have upgraded to cbd 1.2.0, thats great, but i can see that you
> are stil using docker 1.8.3.
>
> I would recommend to upgrad docker as well? After that you shoud see
> 1.10.3
>
> Then you should restart cloudbreak:
>
> cbd kill
> cbd regenerate
> cbd start
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sequenceiq/cloudbreak/issues/1440#issuecomment-200749650>
>



-- 

*Mohamed Moustapha DIOUF - mohamed.diouf@baamtu.com
<mohamed.diouf@baamtu.com>*
Baamtu SARL
Directeur Général
Tél (FR): +33 6.03.84.29.76
Tél : +221 77.092.34.34
Tél : +221 77.552.21.42
http://www.baamtu.com
http://leboncompte.com

**Comment by lalyos** [comment]
I have probably missunderstood your problem. You were talking about am issue which happens on the host which runs the ambari docker container (HDP cluster), while I was suspecting some configuration issue on the host which runs the cloudbreak docker container: Cloudbreak Deployer (cbd for short) host.

So you have docker 1.8.3 on cbd host, but that doesnt effect the docker version on the HDP cluster. The instance forming the HDP cluster are started from AWS/GCP/AZURE images, so they have predefined docker already installed in. For example cbd 1.2.0 is starting instances which have docker 1.9.1.

For short:
- there is no need to update docker on the cbd host
- docker version on the HDP cluster instance are predefined in the image

Now back to you original issue:
on the HDP cluster each host is running a [consul](http://consul.io) container, which provides service registry, and DNS for all other containers on the same host. The error message `Temporary failure in name resolution` suggests that there is an issue with the consul container.

Please ssh in into one of the instacnes, and get the log of consul container:
```
docker logs <HOSTNAME>-consul
```

**Comment by mdiouf** [comment]
Updating docker on cbd host and using 172.17.0.1 as DNS resolve the problem.
Thanks
