### ISSUE TITLE
Azure - Docker containers are being installs to temp disk, causing application data loss

### ISSUE THREAD

**Issue by lockwobr** [sequenceiq/cloudbreak#1527]
I having a problem with our cluster and it seems that the main problem is that the docker is setup to install into the temp disk /mnt/resource and it seems that some times on a reboot that temp disk is lost rendering the node unusable. [Here ](https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-about-disks-vhds/)is some information on azure temp disk.

If you read [this](https://blogs.msdn.microsoft.com/mast/2013/12/06/understanding-the-temporary-drive-on-windows-azure-virtual-machines/) it says 

      When will the data on temporary drive be lost?
      When you resize the VM, When you shutdown or restart your VM, when your VM is moved to a different host server(due to service healing, shutdown and restart), when the host is updated, when the host experiences a hardware failure etc.

So having the docker installed and storing containters on this drive does not make sense, unless I am missing something.

Here is node that has not lost its temp disk:

	[cloudbreak@vmstream-worker5 ~]$ ls /mnt/resource
	DATALOSS_WARNING_README.txt  docker  lost+found
	[cloudbreak@vmstream-worker5 ~]$ cat  /mnt/resource/DATALOSS_WARNING_README.txt
	WARNING: THIS IS A TEMPORARY DISK.

	Any data stored on this drive is SUBJECT TO LOSS and THERE IS NO WAY TO RECOVER IT.

	Please do not use this disk for storing any personal or application data.

	For additional details to please refer to the MSDN documentation at : http://msdn.microsoft.com/en-us/library/windowsazure/jj672979.aspx

here is one that has:

	[cloudbreak@vmstream-worker4 ~]$ ls /mnt/resource
	DATALOSS_WARNING_README.txt  lost+found
	[cloudbreak@vmstream-worker4 ~]$ docker ps
	An error occurred trying to connect: Get http:///var/run/docker.sock/v1.21/containers/json: read unix /var/run/docker.sock: connection reset by peer

**Comment by biharitomi** [comment]
Hi @lockwobr ,

I hope your cbd version is 1.2.x, because there is an option in advanced cluster creation that is able to turn off docker relocation to the temporary disk.
'Relocate Docker Needed' option should be disabled when you [ configure the filesystem of your cluster](https://img42.com/XWYiP)

Br,
Tamas

**Comment by lockwobr** [comment]
Thanks a lot for the information, I will test that out next week and see how that goes. Seems strange that this is a default, at least for azure clusters. Will report back.

**Comment by lockwobr** [comment]
I have verified that this fixes the issue. 

Any thoughts on making this work different at least for azure platform? Maybe this is not the default or have the an other disk attached for docker maybe if the relocate check box is checked?

**Comment by doktoric** [comment]
@lockwobr is 1.3.0 TP we do not using docker by default.
