### ISSUE TITLE
【cloudbreak Development】 Uluwatu could not connect to Cloudbreak

### ISSUE THREAD

**Issue by bendan123812** [sequenceiq/cloudbreak#1535]
hi
Thank you for attention to my problem !
I follow the instructions of the site http://sequenceiq.com/cloudbreak-docs/latest/development/
and build the development environment of cloudbreak。

1、 I execute "cbd start" and than I visited cloudbreak address http://172.24.3.152:3000/
	I click "manage credentials" button and I see the page like this.
       It hive 'Azure','AWS','Mesos'....

2、 Next , I update the Profile file and add CB_SCHEMA_SCRIPTS_LOCATION properties.

    export CB_SCHEMA_SCRIPTS_LOCATION=/opt/workspace/cbwsp/cloudbreak-1.2.4/core/src/main/resources/schema

Than I runner 'cbd util local-dev' and get this output:

`Stopping cbreak_cloudbreak_1... `
		`Migration SUCCESS: cbdb up`
		`Migration SUCCESS: cbdb pending`
		`docker: Error response from daemon: Conflict. The name "/cloudbreak-proxy" is already in use by container 56fcd3a23798e0143e969a3ec07aa604198ae176889b8a1efd8f84d1eaf70d2b. You have to remove (or rename) that container to be able to reuse that name..`
		`See 'docker run --help'.`
	
so , I remove the cloudbreak-proxy container and runner 'cbd util local-dev' again

		`Migration SUCCESS: cbdb up`
		`Migration SUCCESS: cbdb pending`
		`3c055b573c6a2b1a7a2e98b317325b21461408407eb6806249fa7b07d1d6d823`
		
3、 Next , I launch the Cloudbreak application execute the com.sequenceiq.cloudbreak.CloudbreakApplication class with VM options:

		`-XX:MaxPermSize=1024m`
		`-Dcb.cert.dir=/opt/cbd-local/certs`
		`-Dcb.client.id=cloudbreak`
		`-Dcb.client.secret=cbsecret2015`
		`-Dcb.db.port.5432.tcp.addr=172.17.0.1`
		`-Dcb.db.port.5432.tcp.port=5432`
		`-Dspring.cloud.consul.host=172.17.0.1`
		`-Dcb.identity.server.url=http://172.17.0.1:8089`
		`-Dserver.port=9091`
	
I was successful !

		`2016-05-10 12:02:35,511 [main] log:180 INFO  o.a.t.u.n.NioSelectorPool - [owner:spring] [type:springLog] [id:] [name:] Using a shared selector for 	servlet write/read`
		`2016-05-10 12:02:35,535 [main] start:162 INFO  o.s.b.c.e.t.TomcatEmbeddedServletContainer - [owner:spring] [type:springLog] [id:] [name:] Tomcat started on port(s): 9091 (http)`
		`2016-05-10 12:02:35,546 [main] logStarted:57 INFO  c.s.c.CloudbreakApplication - [owner:spring] [type:springLog] [id:] [name:] Started CloudbreakApplication in 36.335 seconds (JVM running for 37.634)`
		
4、 Next , I visited cloudbreak address http://172.24.3.152:3000/

I click "manage credentials" button and I see the page like this.
It hive no 'Azure','AWS','Mesos'....
and I get the error from the browser console:
		GET http://172.24.3.152:3000/accountpreferences 500
		
I think this is because Uluwatu could not connect to Cloudbreak .
can you help me ?
many thanks !!!!

**Comment by biharitomi** [comment]
Hi @bendan123812 ,

I assume that you problem is that the Cloudbreak API moved to '/api/v1' root path and you should use the latest from the Cloudbreak UI that called Uluwatu and you could use it by adding the 'ULUWATU_VOLUME_HOST' variable to your cbd Profile.
My config:
`ULUWATU_VOLUME_HOST=/Users/tbihari/prj/cloudbreak/web/`

If it doesn't do the magic for you, could you please get back with the result of `cbd version` and `cbd env show |grep TAG` commands?

Br,
Tamas

**Comment by bendan123812** [comment]
cd cbd-local
curl https://raw.githubusercontent.com/sequenceiq/cloudbreak-deployer/master/install | sh && cbd --version
cbd update release #1385	
	
cbd version:
```
local version:1.2.1-release-1.2.1-9dd56b1
latest release:1.2.2
[WARN] !!!!!!!!!!!!!!!!!!!!!!!!!!!!
[WARN] Your version is outdated
[WARN] !!!!!!!!!!!!!!!!!!!!!!!!!!!!
[WARN] Please update it by:
  cbd update
```
  
Because I want to develop on the basis of cloudbreak-1.2.4 but cbd-1.2.2 is use cloudbreak-1.2.5 so I ignored the warning .

cbd env show |grep TAG:

```
DOCKER_TAG_ALPINE                 = 3.1
DOCKER_TAG_HAVEGED                = 1.1
DOCKER_TAG_CONSUL                 = 0.5
DOCKER_TAG_REGISTRATOR            = v5
DOCKER_TAG_POSTGRES               = 9.4.1
DOCKER_TAG_UAA                    = 2.7.1
DOCKER_TAG_UAADB                  = v2.7.1
DOCKER_TAG_AMBASSADOR             = 0.5.0
DOCKER_TAG_CERT_TOOL              = 0.0.3
DOCKER_TAG_CBDB                   = 1.2.0
DOCKER_TAG_PCDB                   = 1.2.0
DOCKER_TAG_PERISCOPE              = 1.2.4
DOCKER_TAG_CLOUDBREAK             = 1.2.4
DOCKER_TAG_ULUWATU                = 1.2.4
DOCKER_TAG_SULTANS                = 1.2.4
DOCKER_TAG_CLOUDBREAK_SHELL       = 1.2.4
DOCKER_TAG_MIGRATION              = 1.0.0
DOCKER_TAG_MIGRATION              = 1.0.0
```

I update the Profile  and adding 'ULUWATU_VOLUME_HOST' variable to my cbd Profile . now it like this:

cat Profile:

```
export PUBLIC_IP=172.24.3.152
#export CB_SCHEMA_SCRIPTS_LOCATION=/opt/schema
export CB_SCHEMA_SCRIPTS_LOCATION=/opt/workspace/cbwsp/cloudbreak-1.2.4/core/src/main/resources/schema
export ULUWATU_VOLUME_HOST=/opt/workspace/cbwsp/cloudbreak-1.2.4/web
```

start cbd again

cbd init:

```
Profile already exists, now you are ready to run:
cbd generate
===> Deployer doctor: Checks your environment, and reports a diagnose.
uname: Linux hlg-3p152-gaojun 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
local version:1.2.1-release-1.2.1-9dd56b1
latest release:1.2.2
[WARN] !!!!!!!!!!!!!!!!!!!!!!!!!!!!
[WARN] Your version is outdated
[WARN] !!!!!!!!!!!!!!!!!!!!!!!!!!!!
[WARN] Please update it by:
  cbd update
docker command: OK
docker client version: OK
docker server version: OK
ping 8.8.8.8 on host: OK
ping github.com on host: OK
ping 8.8.8.8 in container: OK
ping github.com in container: OK
```

cbd start:

```
generating docker-compose.yml
generating uaa.yml
Creating cbreak_haveged_1...
Creating cbreak_uluwatu_1...
Creating cbreak_cbdb_1...
Creating cbreak_consul_1...
Creating cbreak_cloudbreak_1...
Creating cbreak_registrator_1...
Creating cbreak_pcdb_1...
Creating cbreak_periscope_1...
Creating cbreak_sultans_1...
Creating cbreak_uaadb_1...
Creating cbreak_logsink_1...
Creating cbreak_logspout_1...
Creating cbreak_identity_1...
Uluwatu (Cloudbreak UI) url:
  http://172.24.3.152:3000
login email:
  admin@example.com
password:
  cloudbreak
```

![image](https://cloud.githubusercontent.com/assets/6983824/15169187/3d8efc36-176b-11e6-90b3-e9657976cf91.png)

cbd util local-dev:

```
Stopping cbreak_cloudbreak_1...
Migration SUCCESS: cbdb up
Migration SUCCESS: cbdb pending
bdbb3080f4776069c050ff7dc8198759e83c03a5b49ee71ac940e3a1c78a8577
```

start cloudbreak-1.2.4 in idea:
To launch the Cloudbreak application execute the com.sequenceiq.cloudbreak.CloudbreakApplication.
it is successful!

Than I request http://172.24.3.152:3000/
but I get an error:

Unable to access this site.
172.24.3.152 refused our requests to connect.

**Comment by bendan123812** [comment]
oh , I know !
I should run Uluwatu on my local machine .

**Comment by bendan123812** [comment]
I read the REAMME.md file in cloudbreak-1.2.4/web and I find run Uluwatu on my local machine is not necessary .
So, I try run Uluwatu use cloudbreak-deployer.
I update the Profile and adding 'ULUWATU_VOLUME_HOST' variable to my cbd Profile .
After regenerate my config files after variable changed I execute 'cbd start':
```
generating docker-compose.yml
generating uaa.yml
Creating cbreak_haveged_1...
Creating cbreak_uluwatu_1...
Creating cbreak_cbdb_1...
Creating cbreak_consul_1...
Creating cbreak_cloudbreak_1...
Creating cbreak_registrator_1...
Creating cbreak_pcdb_1...
Creating cbreak_periscope_1...
Creating cbreak_sultans_1...
Creating cbreak_uaadb_1...
Creating cbreak_logsink_1...
Creating cbreak_logspout_1...
Creating cbreak_identity_1...
Uluwatu (Cloudbreak UI) url:
  http://172.24.3.152:3000
login email:
  admin@example.com
password:
  cloudbreak
```

But I find docker cbreak_uluwatu_1 is not start successful.
I find the error from container log:
```
{"log":"Error: Cannot find module 'express'\n","stream":"stderr","time":"2016-05-11T07:07:40.02270735Z"}
{"log":"    at Function.Module._resolveFilename (module.js:338:15)\n","stream":"stderr","time":"2016-05-11T07:07:40.022761244Z"}
{"log":"    at Function.Module._load (module.js:280:25)\n","stream":"stderr","time":"2016-05-11T07:07:40.02277207Z"}
{"log":"    at Module.require (module.js:364:17)\n","stream":"stderr","time":"2016-05-11T07:07:40.02277838Z"}
{"log":"    at require (module.js:380:17)\n","stream":"stderr","time":"2016-05-11T07:07:40.022784787Z"}
{"log":"    at Object.\u003canonymous\u003e (/uluwatu/server.js:1:77)\n","stream":"stderr","time":"2016-05-11T07:07:40.022800062Z"}
{"log":"    at Module._compile (module.js:456:26)\n","stream":"stderr","time":"2016-05-11T07:07:40.022806844Z"}
{"log":"    at Object.Module._extensions..js (module.js:474:10)\n","stream":"stderr","time":"2016-05-11T07:07:40.022812304Z"}
{"log":"    at Module.load (module.js:356:32)\n","stream":"stderr","time":"2016-05-11T07:07:40.022817811Z"}
{"log":"    at Function.Module._load (module.js:312:12)\n","stream":"stderr","time":"2016-05-11T07:07:40.022872139Z"}
{"log":"    at Function.Module.runMain (module.js:497:10)\n","stream":"stderr","time":"2016-05-11T07:07:40.022880714Z"}
```

**Comment by biharitomi** [comment]
Hi @bendan123812 

I assume you would like to use latest master from Cloudbreak UI and API, so please update your cbd to the latest master by running `cbd update master`, before doing this please destroy the previously created containers by running `cbd kill` and delete the container manually that was created by the `cbd util local-dev` command. Then regenerate your config files by running `cbd regenerate` and starts the deployment with `cbd start`.
If you set the 'ULUWATU_VOLUME_HOST' variable in your profile, the cbd will mount the specified path to the container and Uluwatu should be the latest master.
If a container exited after pushing a `cbd start` please get back with the 'docker logs cbreak_x_1' of that container(s).

Br,
Tamas

**Comment by bendan123812** [comment]
I want to develop on the basis of cloudbreak-1.2.4 but  latest master cbd is use cloudbreak-1.2.5

**Comment by biharitomi** [comment]
The volume host magic of Uluwatu should work with the previous release of cbd, please kill your containers `cbd kill` and regenerate your config files by running `cbd regenerate` after set the variable in your Profile. Starts the deployment again with `cbd start` and let's see the logs of Uluwatu.
Is the Cloudbreak in your Idea started successfully?

**Comment by bendan123812** [comment]
@biharitomi 
many thanks!
I was successful !
Finally , I choose run Uluwatu use cloudbreak-deployer.
At the beginning I execute 'cbd start' but docker cbreak_uluwatu_1 is not start successful.
I find the error from container log:

```
{"log":"Error: Cannot find module 'express'\n","stream":"stderr","time":"2016-05-11T07:07:40.02270735Z"}
{"log":"    at Function.Module._resolveFilename (module.js:338:15)\n","stream":"stderr","time":"2016-05-11T07:07:40.022761244Z"}
{"log":"    at Function.Module._load (module.js:280:25)\n","stream":"stderr","time":"2016-05-11T07:07:40.02277207Z"}
{"log":"    at Module.require (module.js:364:17)\n","stream":"stderr","time":"2016-05-11T07:07:40.02277838Z"}
{"log":"    at require (module.js:380:17)\n","stream":"stderr","time":"2016-05-11T07:07:40.022784787Z"}
{"log":"    at Object.\u003canonymous\u003e (/uluwatu/server.js:1:77)\n","stream":"stderr","time":"2016-05-11T07:07:40.022800062Z"}
{"log":"    at Module._compile (module.js:456:26)\n","stream":"stderr","time":"2016-05-11T07:07:40.022806844Z"}
{"log":"    at Object.Module._extensions..js (module.js:474:10)\n","stream":"stderr","time":"2016-05-11T07:07:40.022812304Z"}
{"log":"    at Module.load (module.js:356:32)\n","stream":"stderr","time":"2016-05-11T07:07:40.022817811Z"}
{"log":"    at Function.Module._load (module.js:312:12)\n","stream":"stderr","time":"2016-05-11T07:07:40.022872139Z"}
{"log":"    at Function.Module.runMain (module.js:497:10)\n","stream":"stderr","time":"2016-05-11T07:07:40.022880714Z"}
```

From the error message I found that I need install node.js and express module.
So , I install node.js and run `npm install && cd app/static && bower install` in Uluwatu's directory.

Than I execute `cbd start` again and docker cbreak_uluwatu_1 is start successful.

now it`s ok !

thanks for your help !

**Comment by biharitomi** [comment]
You are welcome and thanks for reporting the solution! :)
