### ISSUE TITLE
Cannot Create Azure AD Application 

### ISSUE THREAD

**Issue by ThomTel** [sequenceiq/cloudbreak#1553]
Hi, 

im trying to create a azure add apllication using "cbd azure configure-arm"
but im getting following error: 

waiting...
Your application id: d6ac9626-4693-4256-b11b-e79dab052511
waiting...
Your Object id: b7576578-a61c-41ed-b450-5f1a230ef15d
waiting...
1.retry...
---> command failed with exit code: 1
2.retry...
---> command failed with exit code: 1
..and so on ..

Any Idea ? 
Can you provide a manual way to deploy the app ?

Kind Regards 

Thomas

**Comment by biharitomi** [comment]
Hi @ThomTel 

The cbd tool use a docker container that is build from this [github repo.](https://github.com/sequenceiq/azure-cli-tools) You could follow the 'cli_tools' script related part ([This part](https://github.com/sequenceiq/azure-cli-tools/blob/master/cli_tools#L282-L313) do the magic part by using the Azure CLI), of course you could use this script without docker, but the Azure cli needs to be installed.

Br,
Tamas
