### ISSUE TITLE
AWS Cluster Creation Fails

### ISSUE THREAD

**Issue by kgraves-sky** [sequenceiq/cloudbreak#1560]
Abruptly--last week, I can no longer create AWS HDP clusters.   I'm on cloudbreak 1.2.2. It creates the instances, collects metadata then halts.  Previously, such as on May 9th, I was able to connect.  Has there been a new AMI image?

Here is the event history:
5/16/2016 11:14:23 AM devpersonas3 - create in progress: Creating infrastructure
5/16/2016 11:16:10 AM devpersonas3 - update in progress: Infrastructure creation took 106 seconds
5/16/2016 11:16:13 AM devpersonas3 - available: Infrastructure metadata collection finished

In the logs I getting a lot of these in :
loudbreak_1 | 2016-05-16 15:33:46,995 [reactorDispatcher-37] checkStatus:37 INFO  c.s.c.s.s.f.SshCheckerTask - [owner:721b0a36-104e-460b-aeb2-1b49cf37a239] [type:STACK] [id:30] [name:XXXX] Failed to connect ssh: Connection timed out

===> Deployer doctor: Checks your environment, and reports a diagnose.
uname: Linux XXX.XXX.com 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
local version:1.2.2
latest release:1.2.2
docker command exists: OK
docker client version: 1.11.0
docker client version: 1.11.0
ping 8.8.8.8 on host: OK
ping github.com on host: OK
ping 8.8.8.8 in container: OK
ping github.com in container: OK

**Comment by doktoric** [comment]
Hi @kgraves-sky,

Which kind of network setup are you using on AWS?

Br,
R
