### ISSUE TITLE
Azure -can't create cluster when trying to sue an existing subnet in an existing virtual network

### ISSUE THREAD

**Issue by santosh239** [sequenceiq/cloudbreak#1576]
Trying to create cluster in azure using the existing vnet and subnet. Cloudbreak deployer fails to create...Below is the error

Failed to create the stack for CloudContext{id=2, name='abc-cluster', platform='StringType{value='AZURE_RM'}', owner='xxxxx-4498-905c-xxxxxx'} due to: Resource /subscriptions/8xxx-x-xx/resourceGroups/MARKETINGRG/providers/Microsoft.Network/virtualNetworks/MARKETINGVNET
 referenced by resource /subscriptions/80c4c340-xxx-xxxx-xx/resourceGroups/abc-cluster/providers/Microsoft.Network/networkInterfaces/abc-cluster2hostgroupclient11 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.

But I have the resources exist in azure resources
/subscriptions/80c4c340-43a5-42e2-bba4-fe7ead2cbfb6/resourceGroups/MarketingRG/providers/Microsoft.Network/virtualNetworks/MarketingVNET

Other issue is I also have a resource group already existing but every-time a new cluster is created it creates a new resource group, can this be avoides and use one existing resource group ?

**Comment by mhmxs** [comment]
I tried with latest master, there was no issue.
