### ISSUE TITLE
When I Click on the button  Creare credential，there are nothing .

### ISSUE THREAD

**Issue by qigengwei** [sequenceiq/cloudbreak#1584]
I  use the IDEA developing the  cloudbreak-application ,and  the Profile  include  PUBLIC_IP and 
CB_SCHEMA_SCRIPTS_LOCATION.
![image](https://cloud.githubusercontent.com/assets/13830551/15463822/67e9b42a-20fe-11e6-8ea0-07e0a98a903b.png),

**Comment by qigengwei** [comment]
I followed the instruction in the documentation. http://sequenceiq.com/cloudbreak-docs/latest/development/

**Comment by mhmxs** [comment]
Hi @qigengwei ,

Sorry for the late answer, i hope it isn't too late. I have no idea what occurred this issue but i guess not related to environment setup. Maybe browser's net monitor says something (e.g. missing resources). If you want to develop web interface too please extend your Profile file with `export ULUWATU_VOLUME_HOST=[path-of-cloudbreak-source]/cloudbreak/web` and deployer replaces the original interface to your local one.

Please let me know if works or not (or maybe it already gone).
Cheers,
