### ISSUE TITLE
modify  the ambari-server and ambari-agent docker images used by cloudbreak

### ISSUE THREAD

**Issue by jsfeutz** [sequenceiq/cloudbreak#1718]
cbd version 1.3.0
centos: 7
deploying to DC/OS Marathon

I need to create or modify the ambar-server and agent models used by cloudbreak to get out of http_proxy hell as well as different tools I need to add to the container.

default_images:
hortonworks/ambari-server:2.2.1-v20
hortonworks/ambari-agent:2.2.1-v20

Id like to replace them with
internal-repo.myco.com/dev/ambari-server:2.2.1-local
internal-repo.myco.com/dev/ambari-agent:2.2.1-local

How do I tell cloudbreak to use the my mod'd containers? I've tried both the CB_DOCKER_CONTAINER_AMBARI and CB_DOCKER_CONTAINER_AMBARI_WARM vars and doesnt seem to change anything

Thanks in Advance,
@jsfeutz

**Comment by mhmxs** [comment]
Hi @jsfeutz,

We eliminated docker containers from cluster infrastructure in 1.3.0, so container replacement doesn't work any more. If you want to change Ambari version, normally you need to

- build your custom rpms
- create your own [image catalog]( https://github.com/sequenceiq/cloudbreak/blob/master/cloud-common/src/main/resources/application.yml#L130)
- set it as [default ambari](https://github.com/sequenceiq/cloudbreak/blob/master/cloud-common/src/main/resources/application.yml#L116), or configure HDP repository under "Advanced Options" on web UI

But specially 1.3.0 release fixed some Ambari issues by "hard coding" some patch on the image, so we never tried to replace Ambari version with it.
Many improvements happened in Cloudbreak about http(s) proxy support in the last few months. So maybe we have experience with your root issue, and you could forget your custom stuffs.
Is this a production environment? If not i'm suggesting to use 1.5.0 release candidate, simply update your deployer by executing `cbd update rc-1.5` command.

Cheers
