### ISSUE TITLE
CloudResourceStatus, CloudResource and CloudInstance

### ISSUE THREAD

**Issue by klezalaise** [sequenceiq/cloudbreak#1759]
Hello,

I am looking for informations on these 3 classes : CloudResourceStatus, CloudResource and CloudInstance.
I have some difficulties to see how there are suppose to be use in the methods launch from ResourceConnector and collect from MetaDataCollector.
Furthermore, I don't really see how collect is supposed to be use. 
Is this possible to have more information on this ?

**Comment by biharitomi** [comment]
Hi @klezalaise ,

Here you can find the documentation of our SPI(Service Provider Interface):
http://sequenceiq.com/cloudbreak-docs/latest/spi/
I recommend you to check our implementations. Basically there are two types of mechanism that is supported by cloud providers:
 - Template based, where you can define the necessary resources and their relation through some kind of template language (The AWS or OpenStack implementation could be checked)
 - The other solution is when you need to create resources "manually" and associate them to each other (The GCP or NativeOpenStack implementation could be checked in this case)

Please let us know if it is still not clear for you!

Br,
Tamas

**Comment by klezalaise** [comment]
Hello,

Thanks for you response, I found most of the resources I needed checking OpenStack implementation. 
For what I understand 1 CloudInstance represent 1 vm in the cloud.
There is 1 CloudResource for 1 CloudInstance that received Id from platform cloud.
There is 1 CloudResourceStatus for 1 CloudResource that represent state of creation.

Is this normal that the instanceId of every Instance is null ?

**Comment by biharitomi** [comment]
Hello,

Here you can find how the CloudInstance are instantiated:
https://github.com/sequenceiq/cloudbreak/blob/master/core/src/main/java/com/sequenceiq/cloudbreak/converter/spi/StackToCloudStackConverter.java#L76-L87

The instance id will come from the provider and it is part of the CloudInstance. Outside of the SPI layer we store metadata about the provisioned instances and we can just update the instance id in our metadata when the instances have been created and their instance ids are available and could be got from the cloud provider.

**Comment by klezalaise** [comment]
Just to be sure, when we first create the instance, there is no instanceId.
At the first call of collect from MetadataCollector, InstanceId is added to a CloudInstance present in the CloudVmMetadataStatus that is returned ?
