### ISSUE TITLE
[Feature Request] Add ability to pass external database configuration for Ambari using cloudbreak/blueprint

### ISSUE THREAD

**Issue by anurajp** [sequenceiq/cloudbreak#1770]
Ambari services use local postgres database. It would be great if ambari services database configuration can be an input in cloudbreak or blueprint so ambari uses external db when it starts.

Link to hortonworks community forum: https://community.hortonworks.com/questions/44300/using-external-database-for-ambari-via-blueprint-c.html

**Comment by mhmxs** [comment]
On master branch Cloudbreak supports remote database configuration for Ambari. Currently PostgreSQL and MySQL works out of the box. On the web UI  you should find settings under advanced options. On shell we have a new a new command, you have to execute before `cluster create` command:
`database configure --vendor MYSQL --host [host-name] --port [port-number] --name [database-name] --username [user-name] --password [password]`
