### ISSUE TITLE
Cluster creation fails

### ISSUE THREAD

**Issue by yaron-idan** [sequenceiq/cloudbreak#1790]
Trying to create a cluster on AWS using Cloudbreak AMI. After a profile has been configured with proper AWS creds and using mostly resources that came predefined with Cloudbreak cluster creation fails with the following error - 
```
/cbreak_cloudbreak_1 | 2016-07-17 14:13:16,231 [reactorDispatcher-85] accept:38 INFO  c.s.c.s.e.CloudbreakEventHandler - [owner:undefined] [type:CLOUDBREAKEVENTDATA] [id:undefined] [name:undefined] Sending notification with data: CloudbreakEvent{id=22, eventType='CREATE_FAILED', eventTimestamp=Sun Jul 17 14:13:16 UTC 2016, eventMessage='Ambari cluster could not be created. Reason: com.sequenceiq.cloudbreak.orchestrator.exception.CloudbreakOrchestratorFailedException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Duplicate key 10.0.10.140', owner='40cc932b-8177-4429-95f9-cf54999cb3ef', account='seq1234567', cloud='AWS', region='us-east-1', blueprintName='hdp-spark-cluster', instanceGroup='null', blueprintId=2', stackId=2', clusterId=2', clusterName=horton-cluster-new}
```

Any further details I've omitted will be gladly supplied,
Thanks.

**Comment by bbihari** [comment]
Hi, 

Are you trying to create the cluster in an existing VPC?

**Comment by yaron-idan** [comment]
At first yes, but when trying to let Cloudbreak create a new VPC the same error arises.

**Comment by yaron-idan** [comment]
Update - when running the same exact configuration on another region - the cluster was successfully created. Note: there is a running cluster already up in the region failing.

**Comment by mhmxs** [comment]
Issue was picked up [here](https://community.hortonworks.com/questions/45536/using-cloudbreak-to-create-cluster-on-aws.html).
