### ISSUE TITLE
Build dev cloudbreak test image fails on RHEL7.1/PPC64LE

### ISSUE THREAD

**Issue by anuphalarnkar** [sequenceiq/cloudbreak#2056]
**System:**
OS: RHEL 7.1
Arch: ppc64le

**Build steps:**
1. git clone https://github.com/sequenceiq/cloudbreak.git
2. cd cloudbreak/integration-test
3. sudo make

**Summary of Log:**
[cloudbreak-test-fails-18Nov16.txt](https://github.com/sequenceiq/cloudbreak/files/599756/cloudbreak-test-fails-18Nov16.txt)

--- Build dev cloudbreak test image

Sending build context to Docker daemon 122.3 MB
Step 1 : FROM sequenceiq/cloudbreak:1.3.0-dev.77
1.3.0-dev.77: Pulling from sequenceiq/cloudbreak
8b87079b7a06: Pull complete
a3ed95caeb02: Pull complete
1bb8eaf3d643: Pull complete
3e04171ce2e5: Pull complete
ee148f48ebe6: Pull complete
99d613a5ae1f: Pull complete
6b44ee229acb: Pull complete
d2ac3af23a0f: Pull complete
c7eb15983824: Pull complete
cbd32eb80e83: Pull complete
e9fd9c2ea7ed: Pull complete
0f03a85d1407: Pull complete
3ddffe31890f: Pull complete
2a9cf05ebfee: Pull complete
ca49fc953073: Pull complete
Digest: sha256:0f53c777b56735103fc670f3a8aeb43e2ab19de13e0addebf2d7aade23e33855
Status: Downloaded newer image for sequenceiq/cloudbreak:1.3.0-dev.77
 ---> d088fdcf96a0
Step 2 : ADD cloudbreak.jar /
 ---> 5e41b09fc60a
Removing intermediate container 36cf1c56dc6a
Step 3 : RUN rm -rf /schema     && unzip -o cloudbreak.jar schema/* -d /
 ---> Running in d8e3c035976b
standard_init_linux.go:175: exec user process caused "exec format error"
The command '/bin/sh -c rm -rf /schema     && unzip -o cloudbreak.jar schema/* -d /' returned a non-zero code: 1
make: *** [create-image] Error 1

**Comments:**
I feel as I am using a ppc system and the containers that are getting pulled are x86 and hence the error "**exec format error**". Not sure. Just a guess.

Will appreciate any inputs on this ...

Thanks in advance,
Anup Halarnkar

**Comment by mhmxs** [comment]
Hi @anuphalarnkar ,

Sorry for the late answer. Unfortunately PPC doesn't supported, as you mentioned too. Please reopen the issue if you still have the problem on x86.
