### ISSUE TITLE
Support for adding existing security group.

### ISSUE THREAD

**Issue by marut-launch** [sequenceiq/cloudbreak#2064]
We have a requirement of adding existing security group under manage security group on cloudbreak UI which can be used while spinning up cluster instead of creating new security group (we are using AWS).

Current implementation doesn't tie up security group created on cloudbreak UI to cloud-platform.

1) Quick fix
===
Allow creating security group with multiple option of adding new or existing security group (similar to manage network).

Code fixes (For AWS platform)
- UI fix to allow adding existing security group.
- Database to consume this information
- Cloudformation template fix according to type of security group.

Issue with the approach
- Security group will not be tied up with cloud-platform, existing security group will appear for all hostgroups irrespective of cloud-platform.
  
2) Cleaner Fix
====
Allow creating security group per cloud-platform with multiple option of adding new or existing security group (similar to manage network).

Code fixes (For AWS platform)
- UI change to select cloud-platform and multiple option to add new/existing security groups.
- Introduce new columns for marking existing security group and cloud-platform type.
- Cloudformation template fix according to type of security group.

Issue with the approach
- New security group is generic but if its attached to a cloud-platform, user needs to create similar groups for each cloud-platform.

**Comment by doktoric** [comment]
done
