### ISSUE TITLE
Support for using custom ami for building cluster on AWS.

### ISSUE THREAD

**Issue by marut-launch** [sequenceiq/cloudbreak#2092]
We have lot of customization added to ami's ( which can't be done through recipe ) used for building clusters on AWS,
There should be a feature in cloudbreak UI to input custom ami id for building clusters.

Suggested Fixes
====
 - Introduce a check box (Labeled : Custom Image) under "Choose blueprint" tab in create cluster flow.
 - If user checks the "Custom Image", Allow user to enter ami id (Labeled "Image Id")
 - same ami id should be passed on to cloudformation template.

**Comment by bdelamotte** [comment]
Was the custom ami tested at all? I am finding that in version 1.16.1, a necessary file is required to continue the setup of the cluster - /usr/bin/user-data-helper.sh

I've only seen this file in  the default AMI.

**Comment by doktoric** [comment]
@bdelamotte on our default images there are several thing which is preconfigured like this file is already there.

**Comment by bdelamotte** [comment]
@doktoric Do you have a list of pre-configurations that need to be done on that AMI before it will work with Cloudbreak tab? I have to use a custom AMI instead of the default images Cloudbreak provides.

**Comment by doktoric** [comment]
@bdelamotte the image burning process currently not open sourced. Please contact with hortonworks support and we will happy to help you.

**Comment by bdelamotte** [comment]
@doktoric I have opened a case with Hortonworks Support and I have not had any luck in getting that information. Case # is 00129729. Is there any way you can update that case with the relevant information or have someone on the Cloudbreak team contact us?
