### ISSUE TITLE
recipe create with JSON failing

### ISSUE THREAD

**Issue by craftyc0der** [sequenceiq/cloudbreak#2363]
I created a recipe from the console with the command 
`recipe create --name spark --type POST --scriptUrl https://raw.githubusercontent.com/sequenceiq/consul-plugins-spark/master/spark-recipe.json`
It errored out showing:

> + name: spark-recipe,
> /opt/scripts/post/spark: line 2: name:: command not found
> + description: 'sets up Apache Spark on an Ambari cluster,'
> /opt/scripts/post/spark: line 3: description:: command not found
> + properties: '{'
> /opt/scripts/post/spark: line 4: properties:: command not found
> + '},'
> /opt/scripts/post/spark: line 5: },: command not found
> + plugins: '['
> /opt/scripts/post/spark: line 6: plugins:: command not found
> + https://github.com/sequenceiq/consul-plugins-spark.git
> /opt/scripts/post/spark: line 7: https://github.com/sequenceiq/consul-plugins-spark.git: No such file or directory
> + ']'
> /opt/scripts/post/spark: line 8: ]: command not found

I was expecting it to execute the plugin as described in those repos. I have no interest in this particular plugin, but I followed this pattern to create my own plugin and I get the same type of error. Are these plugin capabilities still available?

**Comment by mhmxs** [comment]
Hi @craftyc0der ,

In older versions of Cloudbreak supported complex forms of recipes, but in current you have to pass the script url as `--scriptUrl` instead of a json or toml file.

**Comment by craftyc0der** [comment]
Are you saying that you may only link to bash scripts now? If so, you may want to make note of that in the README for all the "complex" recipes in your github which still suggest they are usable (if only you can guess what the current configuration riddle is currently).

**Comment by mhmxs** [comment]
Could you please paste content's link where we have to change things? I checked official documentation of recipes, and the concept is the same, only the command changed a [bit](https://github.com/sequenceiq/cloudbreak-docs/pull/168/files).

**Comment by craftyc0der** [comment]
The https://github.com/sequenceiq/consul-plugins-spark repo suggests you can do this:
> recipe add --url https://raw.githubusercontent.com/sequenceiq/consul-plugins-spark/master/spark-recipe.json
If you try it, it will throw errors as it tries to execute the json contents rather than parse it.  I think an improvement to the documentation for the plugins would be to say, the plugin functionality is no longer  available in cloudbreak. In the documentation for the recipes, it should likewise make it clear that plugins no longer are allowed and recipes will all be executed as a shell script. There is no parsing of json allowed anymore.

**Comment by mhmxs** [comment]
Yeah. This one is a very old project not changed for two years. The command doesn't work for more than one and a half year, Cloudbreak doesn't use Consul watch plugins, etc. I suggest to follow the latest documentation, which also should contain mistakes, but more up-to-date.
