### ISSUE TITLE
Support AWS i3 instances

### ISSUE THREAD

**Issue by nfillot** [sequenceiq/cloudbreak#2374]
Hello,

Amazon announced new i3 instances : https://aws.amazon.com/blogs/aws/now-available-i3-instances-for-demanding-io-intensive-applications/ for I/O intensive workloads (NVMe storage) 

It would be nice to add it in the instance type list

Regards

**Comment by doktoric** [comment]
added with this pr https://github.com/sequenceiq/cloudbreak/pull/2375
