### ISSUE TITLE
How do I deploy HDP 2.6 ?

### ISSUE THREAD

**Issue by desaiak** [sequenceiq/cloudbreak#2466]
I am using 1.14, how do I deploy HDP 2.6 ?

**Comment by doktoric** [comment]
@desaiak 
You have two choice:
- If you are using 1.14.0 you can deploy HDP-2.6 if you are using a blueprint with HDP-2.6 and you configure the ambari and HDP repository to HDP-2.6 repos.
- Second option is using an rc build (1.14.4 is unreleased currently) which can configure HDP-2.6 automatically if you have HDP-2.6 in your blueprint file
You can install the rc version with: 
```
curl -Ls public-repo-1.hortonworks.com/HDP/cloudbreak/cloudbreak-deployer_1.14.4-rc.21_Linux_x86_64.tgz | sudo tar -xz -C /bin cbd && cbd version
cbd restart
```

**Comment by desaiak** [comment]
Thanks Richard !
Will this command upgrade 1.14 to 1.14.4
In other words can I run it on the server that has 1.14 currently installed ?

**Comment by doktoric** [comment]
@desaiak 
Yes, but then you should run the 'cbd restart' in the deployment folder which /var/lib/cloudbreak-deployment by default

**Comment by desaiak** [comment]
Thanks .. I have now used the latest AMI with 1.14.4
