### ISSUE TITLE
implementing a recipe after the cluster is launched

### ISSUE THREAD

**Issue by desaiak** [sequenceiq/cloudbreak#2554]
Is there a way to install a package using recipe after the cluster is launched ?

**Comment by doktoric** [comment]
@desaiak 
http://sequenceiq.com/cloudbreak-docs/latest/recipes/
with post install script you can install custom packages.

Br,
R

**Comment by desaiak** [comment]
Thanks .. however still not sure how to do that on a cluster which has already been created and running.

**Comment by mhmxs** [comment]
Hi @desaiak ,

There is no way in Cloudbreak to execute recipes after you created a cluster without recipes. Cloudbreak uploads recipes during provision and upscale if you specified any during the initial cluster create request.
