### ISSUE TITLE
HIVE_SERVER HA Support

### ISSUE THREAD

**Issue by mcable1004** [sequenceiq/cloudbreak#2555]
Ambari blueprints support support HiveServer2 configured for HA (https://issues.apache.org/jira/browse/AMBARI-10489).  However, during the blueprint validation, Cloudbreak is expecting on a single hostgroup with HIVE_SERVER, and is throwing the following error:

13:58:23 Failed to create cluster: Incorrect number of 'HIVE_SERVER' components are in '[host_group_master_1, host_group_master_3]' hostgroups: count: 2, min: 1 max: 1

**Comment by mhmxs** [comment]
Hi @mcable1004 ,

Thank you for the report.

**Comment by mhmxs** [comment]
So i did some investigation and this behavior is a "feature". If you are provisioning any HA component you have to disable blueprint validation on the UI under "Advanced Options"

**Comment by mcable1004** [comment]
Why is this a feature?  Shouldn't the blueprint validation be updated to accept HA when components support it?

**Comment by mcable1004** [comment]
Thanks @mhmxs 

Also saw the closed pull request that fixes this for a future release.
