### ISSUE TITLE
user-data-helper.sh non-existent when using custom AMI

### ISSUE THREAD

**Issue by bdelamotte** [sequenceiq/cloudbreak#2601]
I'm launching a cluster on AWS with Cloudbreak using custom AMIs. I see that Cloudbreak spins up new EC2 instances for the cluster and adds user-data. Looking at the user data from curling http://169.254.169.254/latest/user-data/ I see that some variables are set and a script is called. The last line of the script calls /usr/bin/user-data-helper.sh

I sshed into one of the new instances that Cloudbreak spun up and tried to locate this file and it was missing. This was with the custom AMI. When I don't specify a custom AMI and use the defaults, it works just fine.

I assume this is a bug and that the user-data-helper code should be appended to the user data when the instance gets launched, or that I need to bake the user-data-helper.sh file into my AMI. 

This is on version 1.6.1.

**Comment by doktoric** [comment]
related to this: https://github.com/sequenceiq/cloudbreak/issues/2092
