### ISSUE TITLE
Need to create the cluster in existing private VPC

### ISSUE THREAD

**Issue by firemonk9** [sequenceiq/cloudbreak#366]
Ability to create the Cloudbreak cluster in the existing amazon VPC instead of creating the cluster in a new VPC.

**Comment by IainColledge** [comment]
Hi, just been checking out the hosted version of cloudbreak and it looks fantastic, however the first question I wanted to ask is how to deploy in an existing VPC as we deal with data that sometimes cannot leave the country of origin.

Will try and do this as you've outlined above but would second putting this into the API & UI as this would potentially allow self provision for users without requiring them to have AWS expertise.

**Comment by matyix** [comment]
Thanks - we will add this feature and let you know once it's done.

**Comment by jpkey** [comment]
Hi, are there any updates on this topic? I have the requirement to deploy an Hadoop cluster within an existing VPC and its infrastructure.

**Comment by keyki** [comment]
If you create a subnet in the private VPC you can choose that for your cluster. It's already implemented, just use the latest version. http://sequenceiq.com/cloudbreak-docs/latest/

**Comment by jpkey** [comment]
Hey keyki, thanks for the quick answer and hint. I will check it.

**Comment by ramboforever** [comment]
Hi , I have followed the same steps for installing the cloudbreak on AWS using pre built image. But I am not getting any options to select existing VPC in Cloudbreak UI.

**Comment by keyki** [comment]
As I see the pre-built images were not updated, we'll fix it soon. To get this around:
```
cd /var/lib/cloudbreak-deployment/
cbd kill
cbd update
cbd version
cbd regenerate
cbd start
```
Version should be 1.3.0. Sorry about that.

**Comment by ramboforever** [comment]
Great! Its working perfectly fine.. Thanks for support :)
