### ISSUE TITLE
Terminate fails

### ISSUE THREAD

**Issue by desaiak** [sequenceiq/cloudbreak#411]
My coworker created a test cluster and the terminate is failing, when I check the google cloud console there are no VM's running but Cloudbreak UI seems to think its running and the terminate fails.
![screen shot 2015-01-09 at 5 11 23 pm](https://cloud.githubusercontent.com/assets/1720389/5697597/4800108c-99c3-11e4-90c5-ac4c9a06ca4f.png)
![screen shot 2015-01-09 at 5 11 34 pm](https://cloud.githubusercontent.com/assets/1720389/5697598/48098b80-99c3-11e4-8008-f6b4680215a3.png)

**Comment by keyki** [comment]
fixed
