### ISSUE TITLE
single host group blueprints can only be used with single node clusters

### ISSUE THREAD

**Issue by cjcrobin** [sequenceiq/cloudbreak#444]
Hi,

I am new to the cloudbreak and blueprint.
And now I use the following blueprint and group-size=1 to start a one-node testing cluster.  but I get the error as the "single host group blueprints can only be used with single node clusters":

{
  "configurations": [
    {
      "nagios-env": {
        "nagios_contact": "admin@localhost"
      }
    }
  ],
  "host_groups": [
    {
      "name": "master",
      "components": [
        {
          "name": "OOZIE_SERVER"
        },
        {
          "name": "OOZIE_CLIENT"
        },
        {
          "name": "HISTORYSERVER"
        },
        {
          "name": "SUPERVISOR"
        },
        {
          "name": "NAGIOS_SERVER"
        },
        {
          "name": "TEZ_CLIENT"
        },
        {
          "name": "AMBARI_SERVER"
        },
        {
          "name": "APP_TIMELINE_SERVER"
        },
        {
          "name": "GANGLIA_SERVER"
        },
        {
          "name": "HDFS_CLIENT"
        },
        {
          "name": "NODEMANAGER"
        },
        {
          "name": "YARN_CLIENT"
        },
        {
          "name": "MAPREDUCE2_CLIENT"
        },
        {
          "name": "NAMENODE"
        },
        {
          "name": "GANGLIA_MONITOR"
        },
        {
          "name": "RESOURCEMANAGER"
        },
        {
          "name": "HIVE_SERVER"
        },
        {
          "name": "MYSQL_SERVER"
        },
        {
          "name": "HIVE_CLIENT"
        },
        {
          "name": "HIVE_METASTORE"
        }
      ],
      "cardinality": "1"
    }
  ],
  "Blueprints": {
    "blueprint_name": "hive-singlenode-architecture",
    "stack_name": "HDP",
    "stack_version": "2.2"
  }
}

**Comment by doktoric** [comment]
Do you using the hosted version? (which is cloudbreak.sequenceiq.com)

-- 
richard.doktorics@sequenceiq.com

On February 4, 2015 at 10:48:39 AM, Chen Jingci (notifications@github.com) wrote:

Hi,

I am new to the cloudbreak and blueprint.
And now I use the following blueprint and group-size=1 to start a one-node testing cluster. but I get the error as the "single host group blueprints can only be used with single node clusters":

{
"configurations": [
{
"nagios-env": {
"nagios_contact": "admin@localhost"
}
}
],
"host_groups": [
{
"name": "master",
"components": [
{
"name": "OOZIE_SERVER"
},
{
"name": "OOZIE_CLIENT"
},
{
"name": "HISTORYSERVER"
},
{
"name": "SUPERVISOR"
},
{
"name": "NAGIOS_SERVER"
},
{
"name": "TEZ_CLIENT"
},
{
"name": "AMBARI_SERVER"
},
{
"name": "APP_TIMELINE_SERVER"
},
{
"name": "GANGLIA_SERVER"
},
{
"name": "HDFS_CLIENT"
},
{
"name": "NODEMANAGER"
},
{
"name": "YARN_CLIENT"
},
{
"name": "MAPREDUCE2_CLIENT"
},
{
"name": "NAMENODE"
},
{
"name": "GANGLIA_MONITOR"
},
{
"name": "RESOURCEMANAGER"
},
{
"name": "HIVE_SERVER"
},
{
"name": "MYSQL_SERVER"
},
{
"name": "HIVE_CLIENT"
},
{
"name": "HIVE_METASTORE"
}
],
"cardinality": "1"
}
],
"Blueprints": {
"blueprint_name": "hive-singlenode-architecture",
"stack_name": "HDP",
"stack_version": "2.2"
}
}

**Comment by cjcrobin** [comment]
Yes, I use the hosted version. As I use the same blueprint, before the recent update, I can use it to start a standalone cluster, but now I cannot.

**Comment by matyix** [comment]
We no longer support single node clusters (min size is 3) due to a major architectural change/improvement underneath Cloudbreak (as of the latest release we use Consul underneath).

Sorry for any inconvenience - you can always use e.g. https://github.com/sequenceiq/docker-ambari/tree/1.7.0 locally if you'd like to setup single node clusters.

**Comment by cjcrobin** [comment]
Okay, cool, thanks for the information
