### ISSUE TITLE
docker-enter and maven

### ISSUE THREAD

**Issue by desaiak** [sequenceiq/cloudbreak#452]
Is it possible to have docker-enter (nsenter) installed default on all nodes and maven installed by default on all docker images ?
docker-enter need is very obvious.
Maven - most benchmarking projects I clone end up requiring maven so be nice to just have it ?

**Comment by keyki** [comment]
Nsenter is not required to enter into the container: `docker exec -it ambari-agent bash`. 
Would you like maven to be installed in the docker-ambari image which Cloudbreak launches?

**Comment by desaiak** [comment]
Thanks for the docker exec tip.
Yes .. docker-ambari agent so I can install and run benchmarks unless there is another way to do so.
So far I ran the storm benchmark and Hibench and both needed maven.

**Comment by keyki** [comment]
Do you need the benchmarks to run inside the container or is it enough if it's on the host machine?

**Comment by keyki** [comment]
Btw we have [recipes](http://blog.sequenceiq.com/blog/2015/02/02/cluster-extensions-with-cloudbreak-recipes/) which allows you to do custom installations. It's not part of the UI, but with the Cloudbreak-shell you can do such things.
