### ISSUE TITLE
The cluster control block disappear

### ISSUE THREAD

**Issue by cjcrobin** [sequenceiq/cloudbreak#454]
Hi,

I create a standalone before the recent update. But now I cannot find this cluster panel block under the dashboard, I mean the small square block which displays some simple information like how many nodes and up-time on it. But the instance in the AWS is still running, and when i try to stop instance, after maybe 1 or 2 minutes of stopped the instance, the instance will start itself automatically.

**Comment by matyix** [comment]
Hi - we are really sorry for the inconvenience. The last release had major schema changes thus we could not migrate running stacks. 

On AWS we use autoscaling groups - thus if you terminate an instance from EC2 console that actually will come back. Ideally you should always use Cloudbreak API/UI or shell to terminate clusters but in your case (as a workaround solution) please go to CloudFormation of AWS console and terminate the stack from there.
