### ISSUE TITLE
[feature-request] Build cluster on any docker image

### ISSUE THREAD

**Issue by ziombski** [sequenceiq/cloudbreak#537]
It would be great if you provide a functionality such that user could create a cluster from any docker image derived from (currently) sequenceiq/ambari:1.7.0-consul.

**Comment by martonsereg** [comment]
I’m not sure if it’s a good idea to provide this information in the API or especially on the UI. It’s quite error prone and can be misleading. Also this image is quite large and therefore it’s “burned” in the cloud platform image, so it won’t be pulled on every node every time a cluster starts.
If you’d like to extend the functionality of this image I suppose to check out the recipes feature of Cloudbreak, or if that doesn’t suite your needs you can try to fork Cloudbreak and deploy it locally with a different docker image.
What is your use case where you’d like to use a derived image?

**Comment by ziombski** [comment]
Thanks for reply. I described my use case and the problem which gave me idea of deriving an image in another Issue #542 . I'm using recipes currently but they are limited.
