### ISSUE TITLE
[improvement wanted] Recipe timeout

### ISSUE THREAD

**Issue by ziombski** [sequenceiq/cloudbreak#542]
I'm trying to write a new recipe (installing Hue). It seems ok comparing
to existing recipes. However, when I run it with Cloudbreak I got an error:

Cluster installation failed. Error: Operation timed out. Keys not found or don't have the expected value 'FINISHED'.

After many tries and looking through Cloudbreak code I'm guessing that
you set a 1 minute time-out for a command in recipe. Am I right?

How can anything be installed then with such a small timeout? My
makefile takes about 7-8 minutes to execute and I can imagine that other
recipes developers would also be happy to have more flexibility in scripts.

I would suggest to change the timeout to 15, 30 or 60 minutes. I
understand that you might have introduced it to protect user from
command hanging. However, extending timeout with adding a feature of
"log to the event history window in Cloudbreak UI" would solve the
problem as well. In this way one can more easily track the progress of
recipe execution (terminating cluster manually if necessary) and hanged
command would finally terminate automatically.

**Comment by martonsereg** [comment]
#546 fixes the timeout issue:
- there is a much longer default timeout for recipe execution (15 minutes)
- timeout can be specified dynamically per recipe if the default value doesn't fit the use case

it will take a few days until the change will be out in the hosted version
