### ISSUE TITLE
[feature-request] ability to bypass blueprint validation

### ISSUE THREAD

**Issue by seanorama** [sequenceiq/cloudbreak#595]
Feature Request: The ability to bypass Blueprint validation.

I'm continually testing the newest Blueprint functionality and would like to use CloudBreak for this.

CloudBreak currently has it's own validation (separate from Ambari's) which blocks certain Blueprints.

For example: HA Blueprints. CloudBreak marks them as invalid as it does not have that logic yet.

Long-term the logic for such things should be added, but in the short term and as new Ambari versions are released, the ability to bypass validation would be useful. Or a separate CloudBreak environment for such testing.

-- 
Sean Roberts
Hortonworks

**Comment by keyki** [comment]
Hi,

We added an option field to be able to disable the blueprint validation. We'll push the change to production with the next release.
