### ISSUE TITLE
[feature request] Add recover logic for Cloudbreak service

### ISSUE THREAD

**Issue by ading1977** [sequenceiq/cloudbreak#596]
While a stack is in the middle of being created, deleted or updated, and the hosting machine fails for whatever reasons (e.g., power outage), after it is restarted, Cloudbreak is not able to recover and pick up the polling. 

This is a potentially serious problem during stack creation, because after Cloudbreak restarts, the stack is  already running in the cloud provider, and billing is started, but Cloudbreak still show CREATE_IN_PROGRESS.

**Comment by mhmxs** [comment]
Latest version of Cloudbreak contains the ability to restart cluster operations.
