### ISSUE TITLE
AWS credential create failed

### ISSUE THREAD

**Issue by dischord01** [sequenceiq/cloudbreak#601]
I am having issues creating the credential inside of the Cloudbreak UI. 

I am running a self hosted instance of Cloudbreak inside of AWS GovCloud on Amazon Linux AMI 2014.09.2 x86_64 HVM.
 
I used cloudbreak-deployer - cbd (0.1.0-master-f7c9e67 latest version: 0.1.0) to get everything up and running. I am able to login and start to create a AWS credential. It however the AWS credential fails with the following error;

     22:31:51 AWS credential create failed : Could not assume role 'arn:aws-us-gov:iam::12345678910:role/cb-access': check if the role exists and if it's created with the correct external ID: 'provision-ambari' 

Here are the steps I have taken so far;

    su -
    # curl https://raw.githubusercontent.com/sequenceiq/cloudbreak-deployer/master/install | sh && cbd --version
    # mkdir cloudbreak-deployment
    # cd cloudbreak-deployment
    # cbd update master
    # cbd init
    # echo 'PUBLIC_IP=172.x.x.x' > Profile
    # cbd generate
    # cbd pull
    # cbd start

I created a user "CloudBreak" and then created the Role "cb-access" and edited it to allow the Cloudbreak user to assume the Role. 

    {
    "Version": "2012-10-17",
    "Statement": [
     {
       "Sid": "",
       "Effect": "Allow",
       "Principal": {
        "AWS": "arn:aws-us-gov:iam::12345678910:user/CloudBreak"
       },
       "Action": "sts:AssumeRole",
       "Condition": {
         "StringEquals": {
           "sts:ExternalId": "provision-ambari"
          }
         }
        }
      ]
    }

Here is my Policy (In line) for the Role (cb-access);

    {
     "Version": "2012-10-17",
     "Statement": [
      {
       "Effect": "Allow",
       "Action": [
         "cloudformation:*"
        ],
        "Resource": [
          "*"
         ]
       },
      {
        "Effect": "Allow",
        "Action": [
         "ec2:*"
        ],
        "Resource": [
          "*"
         ]
        },
      { 
       "Effect": "Allow",
       "Action": [
         "sns:*"
        ],
        "Resource": [
         "*"
        ]
       },
      {
        "Effect": "Allow",
        "Action": [
          "iam:PassRole"
        ],
        "Resource": [
          "*"
        ]
       },
      {
        "Effect": "Allow",
        "Action": [
         "autoscaling:*"
        ],
        "Resource": [
         "*"
          ]
        }
      ]
    }

When I go to create the credential I give it the following;

    name = cloudbreak
    description = cloudbreak 
    IAM Role ARN = arn:aws-us-gov:iam::12345678910:role/cb-access 
    SSH public key  = ssh-rsa AAAAAAAAA....

Is this the proper method for IAM Roles+Users when hosting your own Cloudbreak? 

Do you think this could be a GovCloud issue?

**Comment by matyix** [comment]
I assume yo are using the Cloudbreak deployer tool? In the `docker-compose.yml` file you will need to configure these two (by default unused) properties: `AWS_ACCESS_KEY_ID` and `AWS_SECRET_KEY` (under cloudbreak/environment). If this is configured than we need to dig deeper - maybe have a Webex. With the deployer tool you can check the logs with `cbd logs`.

By any chance, now that I learnt you use the gov cloud, could we have a quick call next week when you have some time? I am very much interested in your experience with Cloudbreak on that.

**Comment by dischord01** [comment]
Thanks, I will add that to the docker-compose file. I was not aware of that setting. Although I remember in the previous cloudbreak-deployment there were AWS account settings. 

I would be glad to chat sometime. You can contact me here ssollar@mitre.org.
