### ISSUE TITLE
Large blueprint problem?

### ISSUE THREAD

**Issue by lofbele1** [sequenceiq/cloudbreak#642]
Hi

I failed to use the blueprint from below URL with Cloudbreak.
The error message stated that Cloudbreak is not running but other (smaller) blueprints still worked.

Is there a way to try out the below blueprint on Cloudbreak?

https://github.com/uprush/ambari-blueprint-examples/blob/master/blueprints/streaming/streaming.json

Thanks,

- lenny

**Comment by lalyos** [comment]
Hi Lenny,

You were missing the blueprint_name, with the Pullrequest i sent: https://github.com/uprush/ambari-blueprint-examples/pull/1

Cloudbreak accepts it just fine
