### ISSUE TITLE
Choosing the price of the spot instance-Amazon

### ISSUE THREAD

**Issue by AliGouta** [sequenceiq/cloudbreak#675]
We are interested to use Cloudbreak to setup HDP clusters on Amazon. Amazon provides spot instances and we want to use as slave machines. It turns out that in cloudbreak we are forced to set a price higher than 0.1$, although in reality the price of the spot instance may fall down to 0.04. I think it makes sens to add more elasticity regarding the price we want to fix. Is there some ongoing work in that direction ?

**Comment by martonsereg** [comment]
You're right, we should make the threshold lower. I think there's no specific reason for it being 0.1 and I guess it is only validated on the UI - the backend should accept lower values as well.

**Comment by AliGouta** [comment]
Do you think that will be fixed in the upcoming release of cloudbreak ? In the meanwhile, any clue to make it working ? Should I use the native API calls ?

**Comment by martonsereg** [comment]
It is already merged in the UI project (https://github.com/sequenceiq/uluwatu/pull/236), so you can expect it to be available on cloudbreak.sequenceiq.com in a few days.

**Comment by AliGouta** [comment]
Great thank you !

**Comment by martonsereg** [comment]
Also I've checked it now and it turned out that Cloudbreak had a bug that caused all instances to be standard ones instead of spot ones if at least one hostgroup was associated with a non-spot template. I've also fixed it in https://github.com/sequenceiq/cloudbreak/pull/677. It will also be part of the next release.
