### ISSUE TITLE
region eu-central-1 (Frankfurt) is missing

### ISSUE THREAD

**Issue by patlachance** [sequenceiq/cloudbreak#678]
I wanted to patch file core/src/main/java/com/sequenceiq/cloudbreak/EnvironmentVariableConfig.java to add the missing region but couldn't find the packer file used to create base AMI. Is this file publicly available?

**Comment by martonsereg** [comment]
The image builder scripts are in a private repo, however we're planning to make them public soon. I'll create an internal JIRA ticket about the missing region until then.

**Comment by doktoric** [comment]
done
