### ISSUE TITLE
Repository for images?

### ISSUE THREAD

**Issue by buccella** [sequenceiq/cloudbreak#680]
Is there a repository to retrieve images? I didn't find a place mentioned in the docmentation, and a Google search for `cb-centos66-amb200-2015-05-15` didn't turn up much. I did find a link for a VHD image, which I think I can convert for OpenStack purposes, but it would be good to have a known location for images.

**Comment by keyki** [comment]
Unfortunately there isn't. On AWS we can easily make the images public however it's not the case on Azure and GCP. You can't find the images there as they are private. On GCP it is stored in a bucket and on Azure in a Storage Account. Once a new user starts a cluster we copy these images to their account. For OpenStack the image is stored in an AWS bucket which I can happily share with anyone who'd like to launch clusters there (that's what we do anyway). 

We're planning to make the scripts which we use to create the images on the different cloud providers public so everyone could change it anyway they want.
Also we should extend the documentation with it, indeed.

**Comment by buccella** [comment]
@keyki, thanks. I understand this is all work in progress.

Would you kindly share the link for the QCOW2 image?

**Comment by keyki** [comment]
I'm not sure which version of Cloudbreak are you using so you might have to rename the image after the import to match the one Cloudbreak expects.

https://s3-eu-west-1.amazonaws.com/cb-openstack-images/cb-centos66-amb200-2015-05-25.img

**Comment by buccella** [comment]
@keyki, thanks.
