### ISSUE TITLE
Downscale issue with Amazon

### ISSUE THREAD

**Issue by AliGouta** [sequenceiq/cloudbreak#682]
I was testing the autoscaling feature shipped in cloudbreak to my provisioned Hadoop cluster in Amazon, I figured out that adding slave nodes (upscale) works fine. However, this feature does not seem to work if I want to downscale the number of my nodes. I created an alarm like the following:

description time-downscale (172)
time zone GMT+2
cron expression 0 30 14 * * ?

Applied to the following policy:

adjustment type NODE_COUNT
scaling adjustment -1
host group slave
alert time-downscale (ID:172)

Any idea ?

**Comment by keyki** [comment]
Can you tell me how many slave nodes did you have before you wanted to do a decommission?

**Comment by AliGouta** [comment]
4 slaves

My  CLUSTER SCALING CONFIGURATIONS:
cooldown time: 3
cluster size min.: 2
cluster size max: 100

On my Amazon account, in the autoscaling groups:
The number of hosts in the host-group that points to my slaves ranges from Min=1 to Max=4

**Comment by keyki** [comment]
Cloudbreak doesn't allow any hostgroups to go below the replication factor +1 which means you cannot go below 4 nodes.

Other: The cooldown time seems a little small for me as Amazon might not be able to launch new nodes within 3 minutes.

**Comment by AliGouta** [comment]
Thank you, I will make further tests and get back to you!

**Comment by keyki** [comment]
HDFS does not support "decommission flag" yet, so if you have running applications there is nothing to stop them to write to those nodes which we move data from so you might run into issues with. We're constantly making improvements based on the feedbacks. 

The preferred way is to use the cloud storages as input in case of Amazon it's S3 so you'll only have intermediate data on HDFS.
