### ISSUE TITLE
Not able to view files via Namenode UI

### ISSUE THREAD

**Issue by malathit90** [sequenceiq/cloudbreak#697]
The issue can be reproduced as follows:

Go to namenode UI and select Utilities -> Browse files. Then try to download any of the files present in HDFS. The page redirects to the address such as http://ip-172-31-92-103.node.dc1.consul:50075, which is not resolvable from my machine.

**Comment by biharitomi** [comment]
duplicated by https://github.com/sequenceiq/cloudbreak-deployer/issues/67
