### ISSUE TITLE
Role of cbgateway instance

### ISSUE THREAD

**Issue by AliGouta** [sequenceiq/cloudbreak#715]
I was looking at the documentation and did not find anything about the cbgateway instance. When I define my blueprint and start a new cluster on Amazon, the cbgateway is automatically added as an instance which belongs to my cluster. Could you please describe to us in a few words the role of this instance ? If the purpose is to just to setup a HDP cluster, can I turn it off after the cluster creation ?

**Comment by lalyos** [comment]
Hi,

The short answer is that gateway is running ambari server, so its needed. If you want to have a 10 node cluster, cloudbreak starts 10 node each running an ambari agent, and an extra instance dedicated o amber server.

**Comment by AliGouta** [comment]
Thank you so much!
