### ISSUE TITLE
Latest documentation of features available on cloudbreak recipes

### ISSUE THREAD

**Issue by malathit90** [sequenceiq/cloudbreak#718]
Hi,

I recently came  across the document in sequenceiq blog on recipes.

http://blog.sequenceiq.com/blog/2015/02/02/cluster-extensions-with-cloudbreak-recipes/

Is there any documentation available describing the current available features with cloudbreak recipes? If it exists can somebody help me with the link?

Thanks,
Malathi

**Comment by doktoric** [comment]
Hi @malathit90 
I think we have to update this part of our documentation but you can find here a sample for a recipe which installing titan db on any node.
https://github.com/sequenceiq/consul-plugins-titan

**Comment by malathit90** [comment]
Thanks for the help. Let me have a look.

**Comment by malathit90** [comment]
Hi @doktoric 

I followed the steps as mentioned in the README file and followed these steps in creating a cluster with recipe via cloudbreak shell:

recipe add --url https://raw.githubusercontent.com/malathit90/consul-plugins-hue/master/install-hue.json
blueprint select --id 51
credential select --id 50
network select --id 50
instancegroup configure --instanceGroup master --nodecount 1 --templateName minviable-aws 
instancegroup configure --instanceGroup slave_1 --nodecount 1 --templateName minviable-aws 
instancegroup configure --instanceGroup cbgateway  --nodecount 1 --templateName minviable-aws 
hostgroup configure --hostgroup master --recipeIds <recipe id created in step 1>
stack create --name "test-cluster" --region US_EAST_1 
cluster create

But after cluster installation complete, I don't see that the plugin doesn't seem to work as expected. I am installing hue via the recipe. But when I login to the master node, hue is not installed.

Please let me know if I am missing anything.

Thanks,
Malathi
