### ISSUE TITLE
Error message alerts are very difficult to see

### ISSUE THREAD

**Issue by simonellistonball** [sequenceiq/cloudbreak#734]
When you get a long, detailed error this pops up for about a second as a toaster alert, and then a truncated version of the last one appears at the top of the screen. This makes it impossible to read the errors and resolve the problem they represent. An accessible, or more obvious log of errors from the UI would be very helpful.

**Comment by matyix** [comment]
All the error messages are available for the cluster - we collect it using an ELK stack. Under Services you can see all the logs in the Kibana UI. Also errors show up in the Event History.

**Comment by simonellistonball** [comment]
Errors for things like credential management don't appear. At very least a clear link to the full message would be useful from a UX perspective.
