### ISSUE TITLE
Launch cluster with 0 nodes from a given host_group

### ISSUE THREAD

**Issue by simonellistonball** [sequenceiq/cloudbreak#735]
When you launch a cluster, the validation prevents selecting 0 nodes from a given blueprint host_group. For example, It would be useful to be able to have 0 of a compute (RM only) on the initial cluster build, but allow the auto-scaler to add such nodes later.

**Comment by matyix** [comment]
Periscope - the autoscaling part of Cloudbreak is (and for a while will be) tech preview, thus you can't rely on that to autoscale. On the other hand there are Ambari config/hostgroup limitations and Consul minimum cluster size limitations.
