### ISSUE TITLE
Amazon: Creating a cluster on a pre-existing VPC

### ISSUE THREAD

**Issue by AliGouta** [sequenceiq/cloudbreak#773]
I was trying to start a HDP cluster using my proper VPC & internet gateway. The ratioanle is to make the cluster more secure and define my own network ACL rules. I know that many ports need to be active during the provisioning step as well as after the creation of the cluster. 
At the moment, I allowed all outbound traffic  and limited the inbound traffic to some ports (80, 8080, 443,22,...). This makes the cluster provisioning fail since Ambari does not find the mirrors from where is downloads the rpm packages.

My question: do you have some guidelines to make this possible and what should I do to have a safe cluster with limited Access?

**Comment by patlachance** [comment]
It seams this is work in progress as the cloudformation freemarker template file (cloudbreak/core/src/main/resources/templates/aws-cf-stack.ftl) contains code based on a 'existingVPC' variable.
But I couldn't yet find if the feature is complete or not and how to activate it. There is no option yet in the UI so if it works, it must only be available from the cloudreak-shell or using the API.
Anyone can comment on this?

**Comment by biharitomi** [comment]
Hi,

We created a new resource in Cloudbreak that is called 'network' few month ago. You can configure existing VPC-s trough this new resource and assign the appropriate network resource to the cluster at creation.
This is available on our UI too under 'Manage networks' panel.

Br,
Tamas

**Comment by AliGouta** [comment]
Yes, I tested it and it worked. Then, I was able to play with ACLs to reinforce the security. In cloudbreak, the cluster comes with a default security group, I was wondering if it makes sens to let users make their own securitu group. Thank you !

**Comment by biharitomi** [comment]
Yes, you are right.We planned that the users will be able to make their own security groups, but in the GA version only the default and unmodifiable security groups are available in Cloudbreak.

**Comment by AliGouta** [comment]
Thank you !
