### ISSUE TITLE
Cloudbreak-UI: EC2 instances are not initiated

### ISSUE THREAD

**Issue by AliGouta** [sequenceiq/cloudbreak#805]
Apparently, there is a critical issue with Cloudbreak UI during this weekend. I was trying to start a cluster on Amazon as usual. But the process stops at: "available: The creation of infrastructure took 88 seconds". No EC2 instances are launched to build the cluster. I tried both all-service-group and only-ssh-and-ssl options at manage-security-groups, but no one worked.

**Comment by doktoric** [comment]
could you share your template? are you using spot price instances?

**Comment by AliGouta** [comment]
Yes, indeed I am used to run Spot instances to run MapReduce Jobs and terminate the cluster the end of the day. Now, I just tested dedicated instances and it just worked ! However, with spot instances and eventhough I set the price high, it did not work. Any clue ?
Thank you.

**Comment by doktoric** [comment]
Yes Currently I working on this issue because it seems to be Amazon not supporting spot instances on the offical red hat image :( 
https://forums.aws.amazon.com/message.jspa?messageID=341713

**Comment by AliGouta** [comment]
hmm I see thank you !
Do you plan to run docker containers on Red hat instances instead of Centos ?
Thank you :)

**Comment by matyix** [comment]
On AWS is has to, as the CentOS 7 based images can not be made public due to AMI licensing restrictions. Once Cloudbreak is GA you would be able to use any base image contacting sales. Until than for all trials you have to leave with the RHEL 7.0 version and the restriction Amazon implies on the spot price.

**Comment by AliGouta** [comment]
Ok, so before I was able to set spot prices for the EC2 instances because these instances were running Centos 6 right ? Or is it that Amazon recently changed their policies regarding spot instances ?

**Comment by doktoric** [comment]
yes the first sentence is true. We were on Centos6 and now on RedHat.

**Comment by AliGouta** [comment]
Thank you !

**Comment by AliGouta** [comment]
Sorry for the inconvenience, it looks like the cluster does not start (same problem as before) even if I select reserved instances (not spot ones). Do you have any idea on what may cause this issue ? and how to solve it?

Ideally, next time I will start a cluster and keep it running and the end of the day I will just shutdown the EC2 instances and reboot them the day after.

**Comment by skharidehal** [comment]
Can cloudbreak still only launch RHEL 7 nodes or can it launch cent os nodes as well

**Comment by bbihari** [comment]
@skharidehal Yes, Cloudbreak can only launch RedHat nodes on EC2
