### ISSUE TITLE
Unable to complete provisioning on Azure

### ISSUE THREAD

**Issue by boydj** [sequenceiq/cloudbreak#854]
Using cloudbreak.sequenceiq.com.

8/10/2015 4:14:43 PM azure - create in progress: Creating infrastructure
8/10/2015 4:24:07 PM azure - available: Infrastructure creation took 564 seconds
8/10/2015 4:28:36 PM azure - update in progress: Bootstrapping infrastructure cluster
8/10/2015 4:30:50 PM azure - update in progress: Setting up infrastructure metadata
8/10/2015 4:30:51 PM azure - update in progress: Starting Ambari cluster containers
8/10/2015 4:44:04 PM azure - update in progress: Infrastructure creation failed
8/10/2015 4:44:04 PM azure - create failed: Infrastructure creation failed

Cluster Status
com.sequenceiq.cloudbreak.core.CloudbreakException: com.sequenceiq.cloudbreak.orchestrator.exception.CloudbreakOrchestratorFailedException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out

I have 6 running instances in Azure, but nothing working properly. No Ambari dashboard or anything.

**Comment by akanto** [comment]
As I see the Cloudbreak properly launched containers, until 4:33 PM. But after that none of the containers started on slave1-1-azure-20150810201711 machine. It tried to launch 15 times in the next 10 minutes and finally it gave up. The reason for failure was every time a "Socket read timeout" between Swarm manager running on cbgateway-5-azure-20150810202241 and Cloudbreak.

As I see after that the cluster has been deleted, so I am afraid it is quite impossible to figure out what has happened on cbgateway-5-azure-20150810202241 and slave1-1-azure-20150810201711 machines. Could be a kernel panic or the docker daemon died on slave1-1-azure-20150810201711.

**Comment by boydj** [comment]
OK, we've created a new cluster and have left it running. Same problem as before.

This cluster is named morpheuscloudbreak.

**Comment by matyix** [comment]
Thanks for reporting it - looks like this is related to the devicemapper, the socket timeout is just a side effect. We are working on the fix and will let you know when it's done.

**Comment by boydj** [comment]
@matyix Do you need us to leave our cluster running?

**Comment by matyix** [comment]
No - you can terminate it (thanks). You should expect an update on this shorty, as we are releasing a patch for this issue.

**Comment by bahfolkoff** [comment]
any update on this, I'm experiencing the same thing ?

**Comment by matyix** [comment]
Did you tried recently - like today? As we pushed a new release out which should fix this.

**Comment by akanto** [comment]
We have deployed the 1.0.1 version of Cloudbreak around 1.a.m. PST today, which contained the fix regarding SocketTimeouts on Azure. I have checked the logs of Cloudbreak and it did not show any SocketTimeout in the last 8 hours.

**Comment by bahfolkoff** [comment]
Okay, awesome, will check it out

**Comment by bahfolkoff** [comment]
Looks good now, much appreciated.

**Comment by boydj** [comment]
Not working here.

```
com.sequenceiq.cloudbreak.core.CloudbreakException: com.sequenceiq.cloudbreak.orchestrator.exception.CloudbreakOrchestratorFailedException: java.util.concurrent.ExecutionException: com.github.dockerjava.api.DockerException: {"error_description":"currently unavailable"}
```

```
8/14/2015 2:40:40 PM morpheus - create in progress: Creating infrastructure
8/14/2015 2:47:10 PM morpheus - available: Infrastructure creation took 390 seconds
8/14/2015 2:49:49 PM morpheus - update in progress: Bootstrapping infrastructure cluster
8/14/2015 2:59:21 PM morpheus - update in progress: Setting up infrastructure metadata
8/14/2015 2:59:22 PM morpheus - update in progress: Starting Ambari cluster containers
8/14/2015 3:43:25 PM morpheus - update in progress: Cluster could not be synchronized while stack is in update in progress state and cluster is in requested state!
8/14/2015 3:44:17 PM morpheus - update in progress: Infrastructure creation failed
8/14/2015 3:44:17 PM morpheus - create failed: Infrastructure creation failed
```

**Comment by akanto** [comment]
After 60 seconds the Docker returns with the following error message:
```
DockerException: {"error_description":"currently unavailable"}
```
Could you please gather the Docker logs from /var/log/messages from the cluster, please? Meantime I will try to reproduce the same error with the configuration what you have used.

**Comment by boydj** [comment]
Unfortunately it appears that my SSH key isn't working either.
________________________________________

**Comment by adeze** [comment]
happens on GCE too

**Comment by michaelbironneau** [comment]
Same issue here - got a message saying the ConsulWatch container failed to start after the 30 retries. 

Noticed that there was a consul-watch container on one of the masters but not the others (or the slave), but am not sure if this is expected or not.

For the other nodes (the ones without consul-watch) the output of `docker ps -a` is something like this:

```
CONTAINER ID        IMAGE                                   COMMAND                CREATED             STATUS                         PORTS               NAMES
4bdde326d8c8        sequenceiq/ambari-warmup:2.1.0-consul   "/start-agent"         About an hour ago   Up About an hour                                   ambari-agent-14398180361252
b9a98ecd5529        swarm:0.4.0                             "/swarm join --addr=   About an hour ago   Up About an hour               2375/tcp            hostgroupmaster3-3-cbtest-20150817130851-swarm-agent
167ec7f527bd        sequenceiq/consul:v0.5.0-v5             "/bin/start"           About an hour ago   Up About an hour                                   hostgroupmaster3-3-cbtest-20150817130851-consul
dc4d2d4d543a        gliderlabs/alpine:3.1                   "sh -c 'echo '{\n  \   About an hour ago   Exited (0) About an hour ago                       hostgroupmaster3-3-cbtest-20150817130851-copy
```

I was able to SSH into the instances to get the /var/log/messages logs, if you still want them let me know where to send them. The only error messages I could find there were the following:

**On hostgroupclient node and one of the masters (not the one with the consul-watch container)**

```
Jul 31 15:33:05 localhost kdumpctl: cat: write error: Broken pipe
```

and

```
Aug 17 13:11:45 localhost docker: time="2015-08-17T13:11:45.891599091Z" level=warning msg="Running modprobe bridge nf_nat failed with message: insmod /lib/modules/3.10.0-229.7.2.el7.x86_64/kernel/net/llc/llc.ko \ninsmod /lib/modules/3.10.0-229.7.2.el7.x86_64/kernel/net/802/stp.ko \ninsmod /lib/modules/3.10.0-229.7.2.el7.x86_64/kernel/net/bridge/bridge.ko \ninsmod /lib/modules/3.10.0-229.7.2.el7.x86_64/kernel/net/netfilter/nf_conntrack.ko \ninsmod /lib/modules/3.10.0-229.7.2.el7.x86_64/kernel/net/netfilter/nf_nat.ko \n, error: exit status 1"
```

The cluster is still running so let me know if you want any more information.

**Comment by akanto** [comment]
@michaelbironneau have you seen this error on  Azure or GCE? If you are using the hosted environment, then please tell us  your cluster's name.

I am not sure about the kdumpctl message, but the modprobe bridge nf_nat failed is an issue in Docker, but it is harmless as far as I know.

**Comment by michaelbironneau** [comment]
Azure. It's self hosted, installed earlier today so it's the latest version.

Noticed that on the slave there is a consul-watch container with empty status - a while ago think there was a Docker issue where containers could end up like that if the daemon was restarted while they were running, not sure if this could be related.

```
CONTAINER ID        IMAGE                                               COMMAND                CREATED             STATUS                   PORTS               NAMES
cc1ab8f54ab7        sequenceiq/docker-consul-watch-plugn:2.0.0-consul   "/start.sh consul://   About an hour ago                                                consul-watch-14398182414995                        
474d5191d242        sequenceiq/ambari-warmup:2.1.0-consul               "/start-agent"         About an hour ago   Up About an hour                             ambari-agent-14398180361854                        
7c26be380dd4        swarm:0.4.0                                         "/swarm join --addr=   2 hours ago         Up 2 hours               2375/tcp            hostgroupslave1-0-cbtest-20150817130346-swarm-agent
bc86e91b7ba2        sequenceiq/consul:v0.5.0-v5                         "/bin/start"           2 hours ago         Up 2 hours                                   hostgroupslave1-0-cbtest-20150817130346-consul     
970773bc08e6        gliderlabs/alpine:3.1                               "sh -c 'echo '{\n  \   2 hours ago         Exited (0) 2 hours ago                       hostgroupslave1-0-cbtest-20150817130346-copy     
```

**Comment by akanto** [comment]
I am hunting for this bug in the last few days, what I see that after 60sec the Docker API returns "currently_unavailable". There is no error in  docker logs and no error in swarm logs and no error in kernel logs at all. Everything seems quite normal.

We are already on latest swarm (0.4.0) and right now I am trying to update the Docker form 1.7 to  Docker 1.8.1 to check whether it behaves differently.

Another strange thing that it seems that it is reproducible in your Azure account, but it is quite sporadic in our account, and it comes extremely rarely in case which makes testing things much more harder. What is also strange that we are testing in multiple regions and we have never seen this issue in EU West region only in other.

**Comment by michaelbironneau** [comment]
Not sure how reproducible it is - this is the first time it's happened (the time before that got an error saying something about reserved-ip-50 having already been taken but that particular message has not come back up). The failed cluster is still up, happy to share details of the cluster and SSH key if it helps, just let me know where to send them.

**Comment by michaelbironneau** [comment]
Didn't see the "currently_unavailable" message from the Docker API but I'm not sure where to look for it. Had a look at the Swarm logs, there are a lot of error message complaining of name conflicts related to consul-watch, eg.

```
time="2015-08-17T13:34:16Z" level=error msg="HTTP error: Conflict, The name consul-watch-14398182414122 is already assigned to 21564c$
time="2015-08-17T13:34:16Z" level=error msg="HTTP error: Conflict, The name consul-watch-14398182414423 is already assigned to 43ea4f$
time="2015-08-17T13:34:16Z" level=error msg="HTTP error: Conflict, The name consul-watch-14398182413650 is already assigned to 64f3fe$
time="2015-08-17T13:34:16Z" level=error msg="HTTP error: Conflict, The name consul-watch-14398182414624 is already assigned to 00d997$
time="2015-08-17T13:34:16Z" level=error msg="HTTP error: Conflict, The name consul-watch-14398182414995 is already assigned to cc1ab8$
time="2015-08-17T13:34:16Z" level=error msg="HTTP error: Conflict, The name consul-watch-14398182414423 is already assigned to 43ea4f$
time="2015-08-17T13:34:16Z" level=error msg="HTTP error: Conflict, The name consul-watch-14398182413650 is already assigned to 64f3fe$
```

and then a bit later 404s for some of the same containers

```
 time="2015-08-17T13:35:04Z" level=error msg="HTTP error: No such container consul-watch-14398182414624" status=404
```

**Comment by michaelbironneau** [comment]
OK, turns out I *can* reproduce the issue, have just spun up another failed cluster with the exact same problem. I think it may have to do with the template I'm using - a D2 instance, much smaller than the D4 instance in minviableazure (but necessary as I'm testing on my MSDN subscription account with a 20 core limit). So probably *something* gets put under more stress.

This time a couple consul-watch containers start fine, but there's one that starts up as a zombie (empty status) and the swarm can neither start up  a container with the same name or delete it, so that cycle goes on ad infinitum. Maybe you guys could work around that by querying the status of the container and if it comes back empty or "Removal in progress" then just start up one with a different name.

I think the root issue is definitely a docker-related one as `docker info` hangs on the host with the zombie container (but oddly enough all the other docker commands work fine). Will see if I can make a minimal test case to report it on the Docker repo.

**Comment by akanto** [comment]
hi Michael, could you join to HipChat room, please: https://www.hipchat.com/gohd6v0n1

**Comment by michaelbironneau** [comment]
OK, am in meetings for the next two hours but will join after that.

**Comment by boydj** [comment]
Works for us on Azure now.

**Comment by michaelbironneau** [comment]
Yep, works for us too now.

**Comment by matyix** [comment]
Thanks guys for reporting back - again, sorry for the inconvenience and we appreciate your help nailing down this issue.
