### ISSUE TITLE
AmbariOperationFailedException on AWS

### ISSUE THREAD

**Issue by davidgin** [sequenceiq/cloudbreak#881]
Hi,
Trying to create a cluster on aws with cloudbreak 1.0.1. I get following exception:

com.sequenceiq.cloudbreak.service.cluster.AmbariOperationFailedException: Ambari Blueprint could not be added: Specified stack doesn't exist: org.apache.ambari.server.stack.NoSuchStackException: The requested stack doesn't exist. Name='HDP' Version='1'

Both the predefined stack on Cloubreak UI (HDP-2.2) and newer version (HDP-2.3) produce the same above exception

**Comment by keyki** [comment]
What is the stack_version in your blueprint? It complains that the version is 1 which is indeed invalid.

**Comment by davidgin** [comment]
sorry,

it is indeed the version in the blueprint.
I thought the HDP version  specified in the Create cluster determines the  HDP-stack  

.
