### ISSUE TITLE
Install HDP via cloudbreak in exist VPC

### ISSUE THREAD

**Issue by henryon** [sequenceiq/cloudbreak#891]
is it possible for install HDP in exist VPC? or any roadmap for this purpose?
btw, is it possible for us to setup HDP base on our customized image?

**Comment by keyki** [comment]
1, on AWS - yes, on GCP,Azure,OS - soon
2, yes, you just need to override the env variables

**Comment by henryon** [comment]
Thanks @keyki 
my environment 
exist VPC 10.10.0.0/16 has two subnet 10.10.1.0/24 10.10.2.0/24, so it is possible for creating HDP cluster in each of them, I tested it , failed. from log, it shows conflicts.

**Comment by biharitomi** [comment]
Hi @henryon ,
You could create clusters in existing VPC on AWS with Cloudbreak, but it always tries to create a new subnet that is configured in the selected network resource for the cluster. So could not create a cluster within an existing VPC's existing subnet, you should specify an unallocated range of ips for the network resource.

**Comment by henryon** [comment]
Hi @biharitomi  Thanks for your explanation and advise. 
if I want to create cluster in exist VPC.eg:
exist VPC 10.10.0.0/16 has 10.10.1.0/24 and 10.10.2.0/24 subnet. You meanings I can use unallocated range of ips in 10.10.1.0/24. if that, How can I make it. in network setting on cloudbreak UI? seems no option for that. Appreciate your help.

**Comment by biharitomi** [comment]
Hi @henryon ,
So in existing VPC (10.10.0.0/24) that has existing subnets 10.10.1.0/24 and 10.10.2.0/24 you could create clusters with unallocated subnet like 10.10.x.0/24 where x is not 1 and 2 in this case.
On the Cloudbreak UI it is configurable under **'manage networks'** panel's **'create network (AWS)'** form:
![image of aws network creation] (https://raw.githubusercontent.com/sequenceiq/sequenceiq-samples/master/images/create-aws-network.png)

**Comment by matyix** [comment]
We will support for creating clusters inside an existing subnet - for the time being you can reuse a VPC and let Cloudbreak create a subnet for you within.
