### ISSUE TITLE
Cluster creation on openstack failing image not found munchausen

### ISSUE THREAD

**Issue by fpolicano** [sequenceiq/cloudbreak#901]
CBD version 1.0.2 Cluster creation failing with the following error.

cloudbreak_1    | 2015-08-28 18:36:24,707 [threadPoolExecutorDispatcher-60] call:48 INFO  c.s.c.o.ContainerBootstrapRunner - [owner:4b04cfb7-13f6-44d0-9c5e-07c2076b93b9] [type:STACK] [id:63] [name:oscbhdp23] Calling container bootstrap: Munchausen, additional info: com.sequenceiq.cloudbreak.orchestrator.swarm.containers.MunchausenBootstrap@581dcd54
cloudbreak_1    | 2015-08-28 18:36:24,764 [threadPoolExecutorDispatcher-60] call:58 ERROR c.s.c.o.ContainerBootstrapRunner - [owner:4b04cfb7-13f6-44d0-9c5e-07c2076b93b9] [type:STACK] [id:63] [name:oscbhdp23] Container Munchausen failed to start, retrying [30/19] Elapsed time: 57 ms; Reason: No such image: sequenceiq/munchausen:0.5.5 (tag: 0.5.5)
cloudbreak_1    | , additional info: com.sequenceiq.cloudbreak.orchestrator.swarm.containers.MunchausenBootstrap@581dcd54
cloudbreak_1    | 2015-08-28 18:36:29,765 [threadPoolExecutorDispatcher-60] isExitNeeded:74 DEBUG c.s.c.o.ContainerBootstrapRunner - [owner:4b04cfb7-13f6-44d0-9c5e-07c2076b93b9] [type:STACK] [id:63] [name:oscbhdp23] exitCriteriaModel: StackDeletionBasedExitCriteriaModel{stackId=63}, exitCriteria: false
cloudbreak_1    | 2015-08-28 18:36:29,765 [threadPoolExecutorDispatcher-60] isExitNeeded:26 DEBUG c.s.c.c.b.s.StackDeletionBasedExitCriteria - [owner:4b04cfb7-13f6-44d0-9c5e-07c2076b93b9] [type:STACK] [id:63] [name:oscbhdp23] Check isExitNeeded for model: StackDeletionBasedExitCriteriaModel{stackId=63}
ambassador_1    | 2015/08/28 18:36:29 172.17.0.51:39699 -> node1.node.dc1.consul.:5432
cloudbreak_1    | 2015-08-28 18:36:29,795 [threadPoolExecutorDispatcher-60] isExitNeeded:29 DEBUG c.s.c.c.b.s.StackDeletionBasedExitCriteria - [owner:4b04cfb7-13f6-44d0-9c5e-07c2076b93b9] [type:STACK] [id:63] [name:oscbhdp23] Stack fetched: 63, stack: com.sequenceiq.cloudbreak.domain.Stack@4c9619e8
cloudbreak_1    | 2015-08-28 18:36:29,796 [threadPoolExecutorDispatcher-60] isExitNeeded:77 DEBUG c.s.c.o.ContainerBootstrapRunner - [owner:4b04cfb7-13f6-44d0-9c5e-07c2076b93b9] [type:STACK] [id:63] [name:oscbhdp23] isExitNeeded: false

**Comment by akanto** [comment]
could you log in to the launched VM and execute `docker images`, please?

**Comment by fpolicano** [comment]
Sorry for the delayed response. I had to stop the evaluation of cloudbreak to focus on another project. If you could please give me a general idea of what I am looking for after listing the docker images (I assume check to see if munchausen is there) I will take another look when I am able to proceed with the eval. Thank you for the response.

**Comment by fpolicano** [comment]
As requested, please see output from docker images:

REPOSITORY                             TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
sequenceiq/ambari-warmup               2.1.0-consul        c31fe9d05b3b        7 weeks ago         1.618 GB
sequenceiq/ambari                      2.1.0-consul        5240183cbcbc        8 weeks ago         1.581 GB
swarm                                  0.3.0               446e413bd987        8 weeks ago         10.28 MB
sequenceiq/docker-consul-watch-plugn   2.0.0-consul        e49fc445157c        8 weeks ago         68.88 MB
sequenceiq/munchausen                  0.5.3               90c33dfd2b10        9 weeks ago         13.58 MB
sequenceiq/baywatch                    v0.5.3              e3c322d2ab9b        9 weeks ago         400.3 MB
sequenceiq/baywatch-client             v0.5.3              8ece65220274        10 weeks ago        489.6 MB
sequenceiq/logrotate                   v0.5.1              ab04ffc9ba66        10 weeks ago        7.298 MB
gliderlabs/alpine                      3.1                 0114fb636191        12 weeks ago        5.037 MB
sequenceiq/cb-gateway-nginx            0.2                 35889e55658a        3 months ago        132.8 MB
sequenceiq/consul                      v0.5.0-v5           d6c6e9be7232        3 months ago        60.74 MB
sequenceiq/registrator                 v5.2                eb5c1a4b02aa        4 months ago        14.04 MB
ehazlett/cert-tool                     0.0.3               ba1a70abf208        4 months ago        6.393 MB
postgres                               9.4.1               b733b00eb1ae        4 months ago        213.9 MB

It appears I have an older version of munchausen 0.5.3 than what the deployer is looking for 0.5.5. Please advise. I assume this comes over with the image I am attempting to use (cb-centos71-amb210-2015-07-17) Can you instruct me where to find and updated image ?

**Comment by fpolicano** [comment]
I believe I found what I'm looking for.

**Comment by doktoric** [comment]
Hi @fpolicano is it really solved?

**Comment by fpolicano** [comment]
Yes with at least regard to the bootstrap issue. cb-centos71-amb210-2015-08-25 image that has the version of munchausen requested.
