### ISSUE TITLE
Blue print customize HDP version

### ISSUE THREAD

**Issue by henryon** [sequenceiq/cloudbreak#903]
I've tested cloudbreak with default setting and set HDP version to 2.2. but the default HDFS version  is 2.2.6 instead of 2.2.0. is there possible for me to customize it? Thanks.

**Comment by akanto** [comment]
If you are specifying the HDP version to 2.2 then the latest version of HDP will be installed from 2.2 line which is 2.2.6 at the moment.
If you would like to install a specific version of HDP then you need to specify the repo version in the "Show Advanced Options" tab when you launch a cluster.

![screen shot 2015-09-01 at 14 05 01](https://cloud.githubusercontent.com/assets/2838000/9603715/e374a9be-50b2-11e5-8927-af16637a5c8c.png)

**Comment by henryon** [comment]
thanks akanto.

**Comment by henryon** [comment]
Hi @akanto   
there are some error message 
2015/9/2 上午11:21:45 hadoop22-cb - update in progress: Building Ambari cluster; Ambari server ip: 52.21.178.40
2015/9/2 上午11:21:45 hadoop22-cb - create failed: Ambari cluster could not be created. Reason: com.sequenceiq.cloudbreak.service.cluster.AmbariOperationFailedException: Cannot use the specified Ambari stack: AmbariStackDetails{id=50, stack='HDP', version='2.2', os='redhat6', stackRepoId='HDP2.2', utilsRepoId='HDP-UTILS-1.1.0.20', stackBaseURL='http://public-repo-1.hortonworks.com/ambari/centos6/2.x/updates/2.0.1', utilsBaseURL='http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.20/repos/centos6', verify=false}. Error: org.apache.ambari.server.controller.spi.NoSuchResourceException: The specified resource doesn't exist: Stack data, stackName=HDP, stackVersion= 2.2, osType=redhat6, repoId= HDP2.2


actually, I copied above information from my exist hdp box. should be validate.

**Comment by keyki** [comment]
HI, 
the `stackRepoId` should be HDP-2.2
