### ISSUE TITLE
blueprint customize

### ISSUE THREAD

**Issue by henryon** [sequenceiq/cloudbreak#915]
is it possible for us to customize  components by adding standby namenode or standby standby  resource manager node. also is it possible for me to delete cbgateway ? or is it mandotory?

**Comment by matyix** [comment]
All HA supported by Ambari Blueprints are supported by Cloudbreak - https://cwiki.apache.org/confluence/display/AMBARI/Blueprint+Support+for+HA+Clusters. You can't remove the Gateway, as that contains the Ambari Server and other components important for the infrastructure.
