### ISSUE TITLE
HADOOP-12304 - fixed in 2.7.2

### ISSUE THREAD

**Issue by desaiak** [sequenceiq/cloudbreak#917]
When will cloudbreak support Hadoop 2.7.2, current version all object store (S3, WASB, GCS etc) connectivity is broken.

Applications using FileContext fail with the default file system configured to be wasb/s3/etc.
(https://issues.apache.org/jira/browse/HADOOP-12304)

**Comment by matyix** [comment]
Alpesh - this should go through the normal support channel. Also I did sent you an email - lets follow up from there.
