### ISSUE TITLE
cloudbreak openstack SSL error

### ISSUE THREAD

**Issue by krenz444** [sequenceiq/cloudbreak#948]
Hello, I am trying to use cloudbreak in our Openstack environment -- I get this error when attempting to generate credentials:

Openstack credential create failed : Failed to authenticate with OpenStack on endpoint: https://[myurl]:5000/v2.0 due to: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I am using this from the web interface,
Thanks for any possible help

**Comment by biharitomi** [comment]
Hi @krenz444 ,

Your OpenStack endpoint could be reach over SSL, so the SSL certificate should be installed in the java truststore of Cloudbreak running environment/container.

Have you got  this error with our hosted version of Cloudbreak?

**Comment by krenz444** [comment]
Hello @biharitomi, thanks for your assistance,

No, I set up a local version of Cloudbreak hosted on my machine using docker as per the manual.
If you know a way to import an SSL cert into a docker container's java truststore let me know, otherwise I will be looking for a way to do this and let you know the results.

Thanks for your help

**Comment by biharitomi** [comment]
Hello @krenz444 ,

You should exec into the Cloudbreak container by using `docker exec -it cbreak_cloudbreak_1 bash` command and your certificate needs to be imported to the java keytool:
`sudo keytool -import -noprompt -trustcacerts -file xy.com.crt -alias "xy" -keystore /etc/ssl/certs/java/cacerts -storepass changeme`
After that if you still get the same exception then try to restart the container (`docker stop/start`).

Please let us know if this is not worked for you!

Br,
Tamas

**Comment by krenz444** [comment]
@biharitomi 

This did the job, to an extent, I was able to add a credential.

The docker image had a password on the cacerts file, it had been changed from the default "changeit".
I instead moved an existing cacerts file to the docker container and replaced the one at /etc/ssl/certs/java/cacerts

The difficulty was transferring the file to the docker container, I managed to do that with 
cat xy.crt | docker exec -i data sh -c 'cat > xy.crt'

I hope this issue will help you in your future development,
Eric

**Comment by biharitomi** [comment]
@krenz444 

Thanks for letting us know!
Sorry for forgetting to give a hint how to add the certification to the container, it was almost midnight here :)

If you have any questions, please do not hesitate!

Tamas

**Comment by zz22394** [comment]
This problem can be resolved better, 
[Using Self-signed Certificates](https://github.com/sequenceiq/cloudbreak-docs/blob/master/docs/openstack/deployer.md)

> If your OpenStack is secured with a self-signed certificate, you need to import that certificate into Cloudbreak, or else Cloudbreak won't be able to communicate with your OpenStack. To import the certificate, place the certificate file in the generated certs directory /certs/trusted/. The trusted directory does not exist by default, so you need to create it. Cloudbreak will automatically pick up these certificates and import them into its truststore upon start.
