### ISSUE TITLE
Cluster stays in start progress state

### ISSUE THREAD

**Issue by ThomTel** [sequenceiq/cloudbreak#957]
In Cloudbreak our cluster stays in start progress state even if the custer is already started. 
There is no possibility to manage the cluster via cloudbreak anymore. 
When we use the sync button it just says: "update in progress: Cluster could not be synchronized while stack is in update in progress state and cluster is in start in progress state!"

There should be an option to reset the custer state.

Does anyone have a workaround for that problem ?

**Comment by doktoric** [comment]
Are you using the hosted version (cloudbreak.sequenceiq.com)? If yes then what is the name of your  cluster ?

**Comment by ThomTel** [comment]
No - sorry - we use it the DIY way.

**Comment by doktoric** [comment]
In the next release we will fixing this problem but now the best solution is if you change the state in the database to 'AVAILABLE'.
Sorry for the inconvenience

**Comment by ThomTel** [comment]
No problem and thanks for your fast answer !
Could you please give me a hint how to change the stae in database ?

**Comment by martonsereg** [comment]
you'll have to exec into the database container and use the psql command line tool:
```
docker exec -it  cbreak_cbdb_1 bash
psql -U postgres
> update stack set status='AVAILABLE' where name like 'cluster-name';
> update cluster set status='AVAILABLE' where name like 'cluster-name';
```
 
btw how did the cluster got stuck in that phase? Did you restart cloudbreak while there were some pending operations on the cluster, or it simply couldn't be restarted properly and got stuck in that phase forever?

**Comment by ThomTel** [comment]
cool - that worked for me ! Thanks a lot. 
I stoped the cluster in the evening and started it in the next morning. All cluster servers got up but the cbgateway-server so i started it manually. For cloudbreak the cluster was in start progress since that time.
