### ISSUE TITLE
Openstack -- unable to find image

### ISSUE THREAD

**Issue by krenz444** [sequenceiq/cloudbreak#960]
Hello,

When trying to create a new cluster through the interface on my local Cloudbreak running on docker, i am given this error: Failed to create cluster: OpenStack image: CentOS-6.5 not found. 

This is after going into docker-compose.yml and modifying the file to point to that particular image

Here is the output from 'glance image-list' with the same credentials sourced as Cloudbreak, you can see this particular image is already in Openstack.
```
+--------------------------------------+------------------------------------------------------+
| ID                                   | Name                                                 |
+--------------------------------------+------------------------------------------------------+
| 7b39c9f8-7f17-4105-bcdb-476a5e358015 | CentOS-6.5                                           |
| e5bfb195-c934-45ae-af3c-34f649ac9e8f | CentOS-6.5-fast                                      |
| eaa5df15-9c88-4e73-b245-3dfe3258473a | centos6.6-lvm-1.3.4                                  |
| 6e757009-7745-4907-9b09-80f7ed06c1d2 | centos6.6-lvm1.0.6-pl                                |
```

Is my Cloudbreak server looking for the image on some different repository?  Where should I get my Images from?

**Comment by biharitomi** [comment]
Hi @krenz444 ,

Coudbreak requires a specific image that contains the necessary tools/scripts.
If you send the version of your *cbd* tool, then I can send you a download link to S3 that contains the appropriate image of Cloudbreak.

To check your cbd version run:
`cbd version`

Br,
Tamas

**Comment by krenz444** [comment]
Hello,

Thank you,

My cbd version is 1.0.3, I was able to track down the correct image, cb-centos71-amb210-2015-07-22

When the cluster starts, im getting a heat orchestration exception, here is an excerpt from `docker logs cbreak_cloudbreak_1`

```
com.sequenceiq.cloudbreak.core.CloudbreakException: ClientResponseException{message=The template version is invalid: Unknown version (heat_template_version: 2014-10-16). Should be one of: 2012-12-12, 2013-05-23, 2010-09-09, status=400, status-code=BAD_REQUEST}
```

Does this mean we have the wrong version of Openstack?

Thanks,
Eric

**Comment by akanto** [comment]
Hi Eric,

Cloudbreak supports the Juno version of OpenStack at the moment.

Kind regards,
Attila

**Comment by krenz444** [comment]
We have upgraded to Juno and this issue has been fixed.  Thank you
