### ISSUE TITLE
Ambari containers fail to start properly

### ISSUE THREAD

**Issue by chisholm** [sequenceiq/cloudbreak#981]
I've been trying to get Cloudbreak working in the "Govcloud" region of AWS.  The "official" AMIs are not available in this region, so recently the main task for me has been to incrementally modify my own AMI as I run into various types of failures.  I feel like I'm almost there, but I've hit what seems like a weird Docker issue with the Ambari containers (both agent and server).

Version info:
AMI OS: Amazon Linux AMI release 2015.03
Cloudbreak version (and deployer): 1.0.3
Ambari docker image:  sequenceiq/ambari-warmup:2.1.0-consul
Docker version (on the cluster nodes):

    Client version: 1.7.1
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 786b29d/1.7.1
    OS/Arch (client): linux/amd64
    Server version: 1.7.1
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): 786b29d/1.7.1
    OS/Arch (server): linux/amd64

The error from the docker log for those containers looks like:

    + ambari-agent start -v
    Verifying Python version compatibility...
    Using python  /usr/bin/python2.6
    Checking for previously running Ambari Agent...
    chown: cannot access `/var/log/ambari-agent/': No such file or directory
    Starting ambari-agent
    /usr/sbin/ambari-agent: line 147: /var/log/ambari-agent/ambari-agent.out: No such file or directory
    Verifying ambari-agent process status...
    ERROR: ambari-agent start failed

(This is for one of the agents.)  The reason is that the `/var/log/ambari-agent` directory doesn't exist in the container:

    # ls -al /var/log
    total 16
    drwxr-xr-x  4 root root 4096 Sep 25 13:21 .
    drwxr-xr-x 17 root root 4096 Mar  4  2015 ..
    drwxr-xr-x  2 root root 4096 Sep 25 13:18 consul
    drwxr-xr-x  2 root root 4096 Sep 25 13:21 consul-watch

It does exist outside the container though:

    $ ls -al /hadoopfs/fs1/logs/
    total 20
    drwxr-xr-x 5 root root 4096 Sep 25 13:17 .
    drwxr-xr-x 4 root root 4096 Sep 25 13:17 ..
    drwxr-xr-x 2 root root 4096 Sep 25 13:17 ambari-agent
    drwxr-xr-x 2 root root 4096 Sep 25 13:17 ambari-server
    drwxr-xr-x 2 root root 4096 Sep 25 13:17 consul-watch

It looks to me like the container volume mounting configuration is correct.  From `docker inspect`:

    "Volumes": {
        "/data/jars": "/data/jars",
        "/etc/ambari-agent/conf/public-hostname.sh": "/usr/local/public_host_script.sh",
        "/hadoopfs/fs1": "/hadoopfs/fs1",
        "/var/log": "/hadoopfs/fs1/logs"
    },

You can see that same host path, `/hadoopfs/fs1`, is also mounted in the container under the same path, and it doesn't show the ambari directories either:

    # ls -al /hadoopfs/fs1/logs
    total 16
    drwxr-xr-x 4 root root 4096 Sep 25 13:21 .
    drwxr-xr-x 3 root root 4096 Sep 25 13:18 ..
    drwxr-xr-x 2 root root 4096 Sep 25 13:18 consul
    drwxr-xr-x 2 root root 4096 Sep 25 13:21 consul-watch

So as far as I can tell, cloud-init is running the init script, mounting /dev/xvdb and creating those directories correctly.  I can see them outside the containers.  But for some reason, they're not showing up inside the container like they should be.  (And why is the 'consul' directory there, but not visible outside the container??)

As an experiment, I created a docker commandline that (I hope) does the exact same thing Cloudbreak does in Java, by looking at the Cloudbreak source and docker inspect data:

    docker run \
    -v /usr/local/public_host_script.sh:/etc/ambari-agent/conf/public-hostname.sh \
    -v /data/jars:/data/jars \
    -v /hadoopfs/fs1:/hadoopfs/fs1 \
    -v /var/log:/hadoopfs/fs1/logs \
    --name="ambari-agent-14429574786832" \
    -e CLOUD_PLATFORM=AWS \
    -e 'HADOOP_CLASSPATH=/data/jars/*:/usr/lib/hadoop/lib/*' \
    -d \
    fe664ac7ffb7 /start-agent

I ran that on the cluster node directly, without making any changes at all except to remove the old container.  And that worked just fine:

    + ambari-agent start -v
    Verifying Python version compatibility...
    Using python  /usr/bin/python2.6
    Checking for previously running Ambari Agent...
    Starting ambari-agent
    Verifying ambari-agent process status...
    tput: No value for $TERM and no -T specified
    Ambari Agent successfully started
    tput: No value for $TERM and no -T specified
    Agent PID at: /var/run/ambari-agent/ambari-agent.pid
    Agent out at: /var/log/ambari-agent/ambari-agent.out
    Agent log at: /var/log/ambari-agent/ambari-agent.log

So when I start the container manually, it works, but when Cloudbreak does it, it fails!  Here's a snip of cloud-init log where the other disk is set up, but it all looks normal to me:

    + mkdir /hadoopfs
    + (( i=1 ))
    + (( i<=24 ))
    +++ printf %x 98
    ++ printf '\x62'
    + LABEL=b
    + DEVICE=/dev/xvdb
    + '[' -e /dev/xvdb ']'
    ++ tr -s ' \t' ' '
    ++ cut '-d ' -f 2
    ++ grep /dev/xvdb /etc/fstab
    + MOUNTPOINT=
    + '[' -n '' ']'
    + mkfs -E lazy_itable_init=1 -O uninit_bg -F -t ext4 /dev/xvdb
    mke2fs 1.42.12 (29-Aug-2014)
    Creating filesystem with 26214400 4k blocks and 6553600 inodes
    Filesystem UUID: 3bfde4f8-8a4b-4827-befa-dcfa5adc7d36
    Superblock backups stored on blocks:
            32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208,
            4096000, 7962624, 11239424, 20480000, 23887872
    
    Allocating group tables: done
    Writing inode tables: done
    Creating journal (32768 blocks): done
    Writing superblocks and filesystem accounting information: done
    
    + mkdir /hadoopfs/fs1
    + echo /dev/xvdb /hadoopfs/fs1 ext4 defaults,noatime 0 2
    + mount /hadoopfs/fs1

So this is my problem.  Does anyone have any insights into this weird docker behavior?

**Comment by martonsereg** [comment]
When inspecting the container with `docker inspect` do you see the volumes under `Mounts` as well?Here's an example from a Cloudbreak cluster not in gov-cloud:
```
"Mounts": [
        {
            "Source": "/hadoopfs/fs1",
            "Destination": "/hadoopfs/fs1",
            "Mode": "rw",
            "RW": true
        },
        {
            "Source": "/usr/local/public_host_script.sh",
            "Destination": "/etc/ambari-agent/conf/public-hostname.sh",
            "Mode": "rw",
            "RW": true
        },
        {
            "Source": "/data/jars",
            "Destination": "/data/jars",
            "Mode": "rw",
            "RW": true
        },
        {
            "Source": "/hadoopfs/fs1/logs",
            "Destination": "/var/log",
            "Mode": "rw",
            "RW": true
        }
    ],
```

**Comment by martonsereg** [comment]
Also which version of Cloudbreak do you use?

**Comment by chisholm** [comment]
It was Cloudbreak 1.0.3.

I never was able to get back to trying to start a cluster again so I could give you the additional info.  The project is moving into a new phase, and this work has been set aside for now.  So I'll have to close this issue without resolving the problem.  Thanks for trying to help!
