### ISSUE TITLE
Feature Request: Edit Security Groups

### ISSUE THREAD

**Issue by msmullins** [sequenceiq/cloudbreak#988]
Currently the product give you two static options for security groups 'only-ssh-and-ssl' and 'all-services-port'. Unfortunately the all-services-port security group doesn't actually expose all services. Notably it doesn't expose the ports for Hive Server2 (10000) or the Hive Metastore (9083), nor the Data Node (50075) useful for WebHDFS. Can we have the all-services-port security group actually expose all services, or better yet let the user define their own security groups?

**Comment by lalyos** [comment]
Hi @msmullins, thanks for reporting. The intent was to let the user define custom sec groups. I can even see form created for it, but it looks like got removed.

@biharitomi dou you know the reason for why the create button/form is not visible?

**Comment by keyki** [comment]
It is not implemented yet to add new security groups, but it is planned.

**Comment by biharitomi** [comment]
Yes, we separated the security configurations into an individual domain object that called security group and could be managed individually on the API and on the UI side too, we would like to finalize our domain model and let the users get used to it. But the update and the replacement of a security group in case of existing clusters is not so trivial, that needs to be implemented in the near future.

Most of the ports that you requested will be opened in the new version of Cloudbreak:
https://github.com/sequenceiq/cloudbreak/commit/bf55b1dbf5865a1cd7b19f3ffd4587d5f8622d35

**Comment by doktoric** [comment]
@msmullins the work is done on master so the next release will contain this feature. You will able to create new rules on UI and in shell also.
